package org.example.server.authority;

import org.example.server.persistence.JpaNativeRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import java.io.*;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

@Service public class ServerBackupService {
 private final Path root;private final String url,user,password,postgresHome;private final boolean scheduledEnabled;private final JpaNativeRepository db;private volatile LocalDate lastScheduled;
 public ServerBackupService(@Value("${dse.workspace.path:}")String workspace,@Value("${spring.datasource.url}")String url,@Value("${spring.datasource.username}")String user,@Value("${spring.datasource.password}")String password,@Value("${dse.postgres.home:}")String postgresHome,@Value("${dse.backup.enabled:false}")boolean scheduledEnabled,JpaNativeRepository db){this.root=(workspace==null||workspace.isBlank()?Path.of(System.getProperty("user.dir")):Path.of(workspace)).toAbsolutePath().normalize().resolve("Backups").resolve("Server");this.url=url;this.user=user;this.password=password;this.postgresHome=postgresHome==null?"":postgresHome.trim();this.scheduledEnabled=scheduledEnabled;this.db=db;}
 public synchronized BackupFile create(String source)throws IOException{Files.createDirectories(root);Path target=root.resolve("DSE-ERP-Server-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"))+".pgbackup");List<String> command=new ArrayList<>(List.of(tool("pg_dump"),"--format=custom","--no-owner","--no-privileges","--file="+target,"--username="+user,jdbcToPostgresUrl(url)));ProcessBuilder builder=new ProcessBuilder(command).redirectErrorStream(true);builder.environment().put("PGPASSWORD",password==null?"":password);Process process=builder.start();String output=new String(process.getInputStream().readAllBytes());try{if(!process.waitFor(10,java.util.concurrent.TimeUnit.MINUTES)){process.destroyForcibly();throw new IOException("Server backup timed out");}}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IOException(e);}if(process.exitValue()!=0||!Files.isRegularFile(target)||Files.size(target)==0){Files.deleteIfExists(target);throw new IOException("pg_dump failed: "+output);}retain(retention());return new BackupFile(target.getFileName().toString(),Files.size(target),Files.getLastModifiedTime(target).toString(),source);}
 public List<BackupFile> list()throws IOException{Files.createDirectories(root);try(var stream=Files.list(root)){return stream.filter(p->p.getFileName().toString().endsWith(".pgbackup")).sorted(Comparator.comparingLong(this::modified).reversed()).map(p->{try{return new BackupFile(p.getFileName().toString(),Files.size(p),Files.getLastModifiedTime(p).toString(),"SERVER");}catch(IOException e){throw new UncheckedIOException(e);}}).toList();}}
 public byte[] read(String name)throws IOException{Path file=safe(name);if(!Files.isRegularFile(file))throw new FileNotFoundException(name);return Files.readAllBytes(file);}
 public synchronized String stageRestore(String name,byte[] data)throws IOException{if(data==null||data.length<16)throw new IOException("Restore backup is empty");Files.createDirectories(root);Path pending=root.resolve("restore-pending.pgbackup");Files.write(pending,data,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);Files.writeString(root.resolve("restore-pending.marker"),"STAGED "+Instant.now()+" "+safeName(name));return "Restore staged on the server. Restart with scripts/apply-staged-server-restore.ps1 before normal startup.";}
 @Scheduled(initialDelayString="${dse.backup.scheduler-initial-delay-ms:300000}",fixedDelayString="${dse.backup.scheduler-check-ms:3600000}") public void scheduled(){if(!scheduledEnabled)return;try{String schedule=setting("backup.schedule","DAILY").toUpperCase(Locale.ROOT);if("MANUAL".equals(schedule))return;LocalDate today=LocalDate.now();boolean due=!today.equals(lastScheduled)&&(!"WEEKLY".equals(schedule)||today.getDayOfWeek()==DayOfWeek.SUNDAY);if(due){create("SCHEDULED");lastScheduled=today;}}catch(Exception e){System.err.println("Scheduled server backup failed: "+e.getMessage());}}
 private int retention(){try{return Math.max(1,Math.min(365,Integer.parseInt(setting("backup.retention","14"))));}catch(Exception e){return 14;}}private String setting(String key,String fallback){try{String value=db.queryForObject("SELECT setting_value FROM application_setting WHERE setting_key=?",String.class,key);return value==null||value.isBlank()?fallback:value;}catch(Exception e){return fallback;}}private void retain(int count)throws IOException{List<Path> files;try(var stream=Files.list(root)){files=stream.filter(p->p.getFileName().toString().endsWith(".pgbackup")).sorted(Comparator.comparingLong(this::modified).reversed()).toList();}for(int i=count;i<files.size();i++)Files.deleteIfExists(files.get(i));}
 private Path safe(String name){Path file=root.resolve(safeName(name)).normalize();if(!file.startsWith(root))throw new IllegalArgumentException("Invalid backup name");return file;}private static String safeName(String name){return(name==null?"backup.pgbackup":name).replaceAll("[^A-Za-z0-9._-]","_");}private long modified(Path file){try{return Files.getLastModifiedTime(file).toMillis();}catch(IOException e){return 0;}}private String tool(String name){if(postgresHome.isBlank())return name;String executable=System.getProperty("os.name","").toLowerCase().contains("win")?name+".exe":name;return Path.of(postgresHome).resolve("bin").resolve(executable).toString();}private static String jdbcToPostgresUrl(String jdbc){return jdbc.startsWith("jdbc:")?jdbc.substring(5):jdbc;}
 public record BackupFile(String name,long size,String createdAt,String source){}
}
