package org.example.server.admin;
import org.springframework.dao.DuplicateKeyException;
import org.example.server.persistence.JpaNativeRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
@Service
public class AdminService {
 private final JpaNativeRepository jdbc; public AdminService(JpaNativeRepository jdbc){this.jdbc=jdbc;}
 @Transactional(readOnly=true) public List<AdminDtos.UserDto> users(){return jdbc.query("SELECT u.id,u.username,u.full_name,u.email,COALESCE(r.role_name,u.role,'SALES') resolved_role,u.department,COALESCE(u.access_level,'STANDARD'),u.branch,COALESCE(u.active,1),COALESCE(u.locked,0),COALESCE(u.mfa_enabled,0),u.last_login FROM users u LEFT JOIN roles r ON r.id=u.role_id ORDER BY COALESCE(u.full_name,u.username),u.username",(r,i)->new AdminDtos.UserDto(r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),flag(r.getObject(9)),flag(r.getObject(10)),flag(r.getObject(11)),Objects.toString(r.getObject(12),"")));}
 @Transactional(readOnly=true) public AdminDtos.UserDto user(int id){return users().stream().filter(x->x.id()==id).findFirst().orElseThrow(()->new IllegalArgumentException("User not found: "+id));}
 @Transactional(readOnly=true) public List<AdminDtos.RoleDto> roles(){return jdbc.query("SELECT r.id,r.role_name,r.description,r.active,COUNT(u.id) user_count FROM roles r LEFT JOIN users u ON u.role_id=r.id OR (u.role_id IS NULL AND u.role=r.role_name) WHERE r.active=1 GROUP BY r.id,r.role_name,r.description,r.active ORDER BY r.role_name",(r,i)->new AdminDtos.RoleDto(r.getInt(1),r.getString(2),r.getString(3),flag(r.getObject(4)),r.getLong(5)));}
 @Transactional(readOnly=true) public List<AdminDtos.PermissionDto> permissions(String role){boolean admin="ADMIN".equalsIgnoreCase(role)||"ADMINISTRATOR".equalsIgnoreCase(role);return jdbc.query("SELECT p.id,p.module_name,p.action_name,p.description,COALESCE(rp.allowed,0) allowed FROM permissions p JOIN roles r ON r.role_name=? LEFT JOIN role_permission rp ON rp.permission_id=p.id AND rp.role_id=r.id WHERE p.active=1 ORDER BY p.module_name,p.action_name",(r,i)->new AdminDtos.PermissionDto(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),admin||flag(r.getObject(5))),role);}
 @Transactional public void savePermissions(AdminDtos.PermissionSaveRequest req){if(req==null||req.role()==null||"ADMIN".equalsIgnoreCase(req.role())||"ADMINISTRATOR".equalsIgnoreCase(req.role()))return;Integer rid=jdbc.queryForObject("SELECT id FROM roles WHERE role_name=?",Integer.class,req.role()); if(rid==null)throw new IllegalArgumentException("Role not found");jdbc.update("DELETE FROM role_permission WHERE role_id=?",rid);for(var p:req.permissions())jdbc.update("INSERT INTO role_permission(role_id,permission_id,allowed) VALUES(?,?,?)",rid,p.id(),p.allowed()?1:0);}
 @Transactional public AdminDtos.UserDto saveUser(AdminDtos.UserSaveRequest d){if(d.id()==null){jdbc.update("INSERT INTO users(username,password,full_name,role,role_id,email,active,locked,mfa_enabled,department,branch,access_level) VALUES(?,?,?,?,(SELECT id FROM roles WHERE role_name=?),?,?,?,?,?,?,?)",d.username(),d.password(),d.fullName(),d.role(),d.role(),d.email(),d.active()?1:0,d.locked()?1:0,d.mfaEnabled()?1:0,d.department(),d.branch(),d.accessLevel());}else{if(d.password()!=null&&!d.password().isBlank())jdbc.update("UPDATE users SET username=?,full_name=?,email=?,role=?,role_id=(SELECT id FROM roles WHERE role_name=?),active=?,locked=?,mfa_enabled=?,department=?,branch=?,access_level=?,password=? WHERE id=?",d.username(),d.fullName(),d.email(),d.role(),d.role(),d.active()?1:0,d.locked()?1:0,d.mfaEnabled()?1:0,d.department(),d.branch(),d.accessLevel(),d.password(),d.id());else jdbc.update("UPDATE users SET username=?,full_name=?,email=?,role=?,role_id=(SELECT id FROM roles WHERE role_name=?),active=?,locked=?,mfa_enabled=?,department=?,branch=?,access_level=? WHERE id=?",d.username(),d.fullName(),d.email(),d.role(),d.role(),d.active()?1:0,d.locked()?1:0,d.mfaEnabled()?1:0,d.department(),d.branch(),d.accessLevel(),d.id());}return d.id()==null?users().stream().filter(x->x.username().equalsIgnoreCase(d.username())).findFirst().orElseThrow():user(d.id());}
 @Transactional public void deleteUser(int id){jdbc.update("DELETE FROM users WHERE id=?",id);}
 @Transactional public void resetPassword(int id,String password){jdbc.update("UPDATE users SET password=?,failed_attempts=0,locked=0 WHERE id=?",password,id);}
 @Transactional public void setLocked(int id,boolean locked){jdbc.update("UPDATE users SET locked=? WHERE id=?",locked?1:0,id);}
 @Transactional public AdminDtos.RoleDto saveRole(AdminDtos.RoleSaveRequest d){String name=d.name()==null?"":d.name().trim().toUpperCase(Locale.ROOT);if(d.id()==null){jdbc.update("INSERT INTO roles(role_name,description,active) VALUES(?,?,?)",name,d.description(),d.active()?1:0);jdbc.update("INSERT INTO role_permission(role_id,permission_id,allowed) SELECT (SELECT id FROM roles WHERE role_name=?),id,0 FROM permissions ON CONFLICT(role_id,permission_id) DO NOTHING",name);}else{String old=jdbc.queryForObject("SELECT role_name FROM roles WHERE id=?",String.class,d.id());jdbc.update("UPDATE roles SET role_name=?,description=?,active=? WHERE id=?",name,d.description(),d.active()?1:0,d.id());if(old!=null&&!old.equals(name))jdbc.update("UPDATE users SET role=? WHERE role=?",name,old);}return roles().stream().filter(x->x.name().equalsIgnoreCase(name)).findFirst().orElseThrow();}
 @Transactional public void deleteRole(int id){jdbc.update("DELETE FROM roles WHERE id=?",id);}
 @Transactional public void audit(AdminDtos.AuditRequest d){try{jdbc.update("INSERT INTO activity_log(entity_type,entity_id,action,detail,created_by) VALUES(\'USER\',?,?,?,\'System\')",d.userId(),d.action(),d.detail());}catch(Exception ignored){}}
 private boolean flag(Object v){if(v==null)return false;if(v instanceof Boolean b)return b;String s=String.valueOf(v);return "1".equals(s)||"t".equalsIgnoreCase(s)||"true".equalsIgnoreCase(s);}
}
