package org.example.server.reconciliation;

import org.example.server.util.BusinessClock;

import org.example.server.persistence.entity.*;
import org.example.server.persistence.JpaNativeRepository;
import org.example.server.returns.ReturnService;
import org.example.server.persistence.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.PageRequest;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;

@Service
public class BankReconciliationService {
 private static final Set<String> RESOLVED=Set.of("MATCHED","EXPENSE","IGNORED");
 private final BankStatementImportRepository imports; private final BankStatementTransactionRepository txs; private final BankReconciliationAllocationRepository allocations; private final BankReconciliationAuditRepository audits; private final PaymentRecordRepository payments; private final SalesHeaderRepository sales; private final PurchaseHeaderRepository purchases; private final FinanceRegisterRepository finance; private final JpaNativeRepository jdbc; private final ReturnService returnService;
 public BankReconciliationService(BankStatementImportRepository imports,BankStatementTransactionRepository txs,BankReconciliationAllocationRepository allocations,BankReconciliationAuditRepository audits,PaymentRecordRepository payments,SalesHeaderRepository sales,PurchaseHeaderRepository purchases,FinanceRegisterRepository finance,JpaNativeRepository jdbc,ReturnService returnService){this.imports=imports;this.txs=txs;this.allocations=allocations;this.audits=audits;this.payments=payments;this.sales=sales;this.purchases=purchases;this.finance=finance;this.jdbc=jdbc;this.returnService=returnService;}

 @Transactional
 public BankReconciliationDtos.ImportResult importStatement(BankReconciliationDtos.ImportRequest r){
  if(r==null||blank(r.bankAccount())||blank(r.sourceFingerprint()))throw new IllegalArgumentException("Bank account and source fingerprint are required.");
  var prior=imports.findBySourceFingerprint(r.sourceFingerprint()); if(prior.isPresent())throw new IllegalStateException("This exact bank statement file has already been imported.");
  BankStatementImportEntity b=new BankStatementImportEntity(); b.setBankName(blank(r.bankName())?"Bank":r.bankName().trim());b.setBankAccount(r.bankAccount().trim());b.setAccountHolder(r.accountHolder());b.setStatementFrom(r.statementFrom());b.setStatementTo(r.statementTo());b.setCurrency(blank(r.currency())?"INR":r.currency());b.setOpeningBalance(r.openingBalance());b.setClosingBalance(r.closingBalance());b.setSourceFingerprint(r.sourceFingerprint());b.setSourceFileName(r.sourceFileName());b.setSourceCsv(r.sourceCsv());b.setImportedBy(r.importedBy());b.setTransactionCount(0);b.setTotalDebit(0d);b.setTotalCredit(0d);b.setReconciledCount(0);b.setReconciliationPercent(0d);b=imports.save(b);
  int added=0,dupes=0; double debit=0,credit=0;
  if(r.rows()!=null)for(var row:r.rows()){
   if(blank(row.transactionFingerprint())||txs.existsByTransactionFingerprint(row.transactionFingerprint())){dupes++;continue;}
   BankStatementTransactionEntity t=new BankStatementTransactionEntity();t.setImportBatch(b);t.setSourceRowNumber(row.sourceRowNumber());t.setTransactionTimestamp(row.transactionTimestamp());t.setTransactionDate(row.transactionDate());t.setValueDate(row.valueDate());t.setOriginalDescription(row.description());t.setOriginalReference(row.reference());t.setDebitAmount(row.debit());t.setCreditAmount(row.credit());t.setBalance(row.balance());t.setTransactionFingerprint(row.transactionFingerprint());txs.save(t);applySuggestion(t);added++;debit+=row.debit();credit+=row.credit();audit(t,"IMPORTED","Imported from "+r.sourceFileName(),null,t.getStatus(),r.importedBy());
  }
  if(added==0){imports.delete(b);throw new IllegalStateException("All transactions in this statement were already imported.");}
  b.setTransactionCount(added);b.setTotalDebit(debit);b.setTotalCredit(credit);imports.save(b);refreshBatch(b.getId());return new BankReconciliationDtos.ImportResult(batch(b),added,dupes);
 }

 public List<BankReconciliationDtos.BatchDto> batches(){return imports.findAllByOrderByImportedAtDesc().stream().map(this::batch).toList();}
 public BankReconciliationDtos.SourceDto source(Long importId){var b=imports.findById(importId).orElseThrow(()->new IllegalArgumentException("Statement batch not found."));return new BankReconciliationDtos.SourceDto(b.getSourceFileName(),b.getSourceFingerprint(),b.getSourceCsv());}
 public List<BankReconciliationDtos.TransactionDto> transactions(Long importId){
  return mapTransactions(txs.findByImportBatchIdOrderByTransactionTimestampAscIdAsc(importId));
 }
 public BankReconciliationDtos.TransactionPage transactionPage(Long importId,int page,int size,String status,String direction,String fromDate,String toDate,String queryText){
  int safePage=Math.max(0,page),safeSize=Math.max(10,Math.min(size,100));
  String safeStatus=up(status),safeDirection=up(direction);if(safeDirection.isBlank())safeDirection="ALL";
  var result=txs.searchPage(importId,safeStatus,safeDirection,safe(fromDate).trim(),safe(toDate).trim(),safe(queryText).trim(),PageRequest.of(safePage,safeSize));
  return new BankReconciliationDtos.TransactionPage(mapTransactions(result.getContent()),metrics(importId),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages());
 }
 public BankReconciliationDtos.Metrics metrics(Long importId){
  var m=txs.aggregateMetrics(importId);
  long total=m==null?0:m.getTotal(),resolved=m==null?0:m.getReconciled();
  double pct=total==0?0:resolved*100d/total;
  String status=total==0?"IMPORTED":resolved==total?"FULLY RECONCILED":resolved==0?"IMPORTED":"PARTIALLY RECONCILED";
  return new BankReconciliationDtos.Metrics((int)total,(int)(m==null?0:m.getUnmatched()),(int)(m==null?0:m.getSuggested()),(int)(m==null?0:m.getMatched()),(int)(m==null?0:m.getExpenses()),(int)(m==null?0:m.getIgnored()),(int)(m==null?0:m.getReview()),m==null?0:m.getTotalCredits(),m==null?0:m.getTotalDebits(),(int)resolved,pct,status);
 }

 @Transactional public List<BankReconciliationDtos.CandidateDto> suggest(Long id){var t=reqTxForUpdate(id);applySuggestion(t);txs.save(t);refreshBatch(t.getImportBatch().getId());return candidates(id);}
 public List<BankReconciliationDtos.CandidateDto> candidates(Long id){var t=reqTx(id);var out=candidatesFor(t);out.sort(Comparator.comparingDouble(BankReconciliationDtos.CandidateDto::confidence).reversed().thenComparingDouble(x->Math.abs(x.outstanding()-bankAmount(t))));return out.stream().limit(30).toList();}

 @Transactional public BankReconciliationDtos.OperationResult match(Long id,BankReconciliationDtos.MatchRequest r){
  var t=reqTxForUpdate(id);ensureProcessable(t);if(r==null||r.allocations()==null||r.allocations().isEmpty())throw new IllegalArgumentException("Select at least one eligible Sale, Purchase or Return refund transaction.");
  double bank=bankAmount(t),sum=r.allocations().stream().mapToDouble(BankReconciliationDtos.AllocationRequest::amount).sum();if(!Double.isFinite(sum)||Math.abs(sum-bank)>.01)throw new IllegalArgumentException("Allocated amount must equal the bank transaction amount ("+fmt(bank)+").");
  boolean credit=n(t.getCreditAmount())>0;Set<String> allowed=credit?Set.of("SALE","PURCHASE_RETURN"):Set.of("PURCHASE","SALES_RETURN");for(var a:r.allocations())if(!allowed.contains(up(a.targetType())))throw new IllegalArgumentException("Bank direction can only match "+String.join(" or ",allowed)+" transactions.");
  FinanceRegisterEntity f=new FinanceRegisterEntity();f.setVoucherNo("BST-"+id);f.setVoucherType(credit?"BANK DEPOSIT":"BANK WITHDRAWAL");f.setVoucherDate(t.getTransactionDate());f.setCategory(credit?"Deposit":"Withdrawal");f.setReferenceNo(t.getOriginalReference());f.setAmount(bank);f.setPaymentMode("Bank Statement");f.setNotes("Matched from imported bank statement: "+safe(t.getOriginalDescription()));f.setAccountName(t.getImportBatch().getBankName()+" - "+t.getImportBatch().getBankAccount());f.setReconciled(1);f.setCreatedAt(BusinessClock.nowUtcText());f=finance.save(f);
  for(var a:r.allocations()){
   double amount=a.amount();if(!Double.isFinite(amount)||amount<=0)throw new IllegalArgumentException("Allocation amount must be a finite number greater than zero.");String target=up(a.targetType());Integer partyId=null,paymentId=null;String docNo="",partyName="";
   if("SALE".equals(target)){var sale=sales.findByIdForUpdate(a.targetId()).orElseThrow(()->new IllegalArgumentException("Sales invoice not found."));if(cancelled(sale.getDocumentStatus()))throw new IllegalStateException("The selected Sales invoice is deleted or cancelled.");double outstanding=Math.max(0,n(sale.getTotalAmount())-n(sale.getPaidAmount()));if(amount>outstanding+.01)throw new IllegalArgumentException("Allocation exceeds outstanding balance for "+sale.getInvoiceNo());double paid=n(sale.getPaidAmount())+amount;sale.setPaidAmount(paid);sale.setPaymentStatus(paid+0.01>=n(sale.getTotalAmount())?"PAID":"PARTIAL");sales.save(sale);partyId=sale.getCustomer()==null?null:sale.getCustomer().getId();partyName=sale.getCustomer()==null?"":safe(sale.getCustomer().getName());docNo=sale.getInvoiceNo();PaymentRecordEntity pr=new PaymentRecordEntity();pr.setDocumentType("SALE");pr.setDocumentId(a.targetId());pr.setPaymentDate(t.getTransactionDate());pr.setAmount(amount);pr.setPaymentMode("Bank Statement");pr.setReferenceNo(t.getOriginalReference());pr.setNotes("Reconciled from bank statement transaction #"+t.getId());pr.setCreatedBy(org.example.server.security.CurrentUser.require().username());pr.setReceivedFrom("Bank Statement");pr.setPaymentType("BANK_RECONCILIATION");paymentId=payments.save(pr).getId();}
   else if("PURCHASE".equals(target)){var purchase=purchases.findByIdForUpdate(a.targetId()).orElseThrow(()->new IllegalArgumentException("Purchase invoice not found."));if(cancelled(purchase.getDocumentStatus())||purchaseLifecycleLocked(purchase.getDocumentStatus()))throw new IllegalStateException("The selected Purchase invoice is not eligible for reconciliation (Draft, Returned, Deleted or Cancelled).");double outstanding=Math.max(0,n(purchase.getTotalAmount())-n(purchase.getPaidAmount()));if(amount>outstanding+.01)throw new IllegalArgumentException("Allocation exceeds outstanding balance for "+purchase.getInvoiceNo());double paid=n(purchase.getPaidAmount())+amount;purchase.setPaidAmount(paid);purchase.setPaymentStatus(paid+0.01>=n(purchase.getTotalAmount())?"PAID":"PARTIAL");purchases.save(purchase);partyId=purchase.getSupplier()==null?null:purchase.getSupplier().getId();partyName=purchase.getSupplier()==null?"":safe(purchase.getSupplier().getName());docNo=purchase.getInvoiceNo();PaymentRecordEntity pr=new PaymentRecordEntity();pr.setDocumentType("PURCHASE");pr.setDocumentId(a.targetId());pr.setPaymentDate(t.getTransactionDate());pr.setAmount(amount);pr.setPaymentMode("Bank Statement");pr.setReferenceNo(t.getOriginalReference());pr.setNotes("Reconciled from bank statement transaction #"+t.getId());pr.setCreatedBy(org.example.server.security.CurrentUser.require().username());pr.setReceivedFrom(partyName);pr.setPaymentType("BANK_RECONCILIATION");paymentId=payments.save(pr).getId();}
   else {Map<String,Object> rr=returnTarget(a.targetId(),target);docNo=Objects.toString(rr.get("no"),"");partyId=((Number)rr.get("party_id")).intValue();partyName=Objects.toString(rr.get("party"),"");double total=((Number)rr.get("total")).doubleValue(),refunded=((Number)rr.get("refunded")).doubleValue(),outstanding=Math.max(0,total-refunded);if(amount>outstanding+.01)throw new IllegalArgumentException("Allocation exceeds refund balance for "+docNo);LocalDate refundDate=date(t.getTransactionDate());if(refundDate==null)throw new IllegalStateException("Bank transaction date is invalid for return refund posting.");paymentId=jdbc.queryForObject("INSERT INTO return_refund(return_no,refund_date,amount,payment_mode,reference_no,bank_account,refunded_party,notes,refund_type,created_by,created_at,bank_statement_transaction_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id",Integer.class,docNo,refundDate,amount,"Bank Statement",safe(t.getOriginalReference()),t.getImportBatch().getBankName()+" - "+t.getImportBatch().getBankAccount(),partyName,"Reconciled from bank statement transaction #"+t.getId(),"BANK_RECONCILIATION",org.example.server.security.CurrentUser.require().username(),BusinessClock.nowUtcText(),t.getId());returnService.syncRefundState(docNo);}
   if(r.allocations().size()==1)f.setPartyId(partyId);BankReconciliationAllocationEntity al=new BankReconciliationAllocationEntity();al.setStatementTransactionId(t.getId());al.setTargetType(target);al.setTargetId(a.targetId());al.setAllocatedAmount(amount);al.setPaymentRecordId(paymentId);al.setFinanceEntryId(f.getId());al.setCreatedBy(org.example.server.security.CurrentUser.require().username());allocations.save(al);audit(t,"MATCHED","Allocated "+fmt(amount)+" to "+docNo,t.getStatus(),"MATCHED",r.user());
  }
  finance.save(f);String old=t.getStatus();t.setStatus("MATCHED");t.setSuggestedConfidence(null);txs.save(t);if(!"MATCHED".equals(old))audit(t,"STATUS_CHANGED","Match confirmed",old,"MATCHED",r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Bank transaction matched successfully.","MATCHED",f.getId());
 }
 @Transactional public BankReconciliationDtos.OperationResult expense(Long id,BankReconciliationDtos.ExpenseRequest r){var t=reqTxForUpdate(id);ensureProcessable(t);if(n(t.getDebitAmount())<=0)throw new IllegalArgumentException("Only debit transactions can be moved to Expense Entry.");FinanceRegisterEntity f=new FinanceRegisterEntity();f.setVoucherNo("BSE-"+id);f.setVoucherType("EXPENSE");f.setVoucherDate(t.getTransactionDate());f.setCategory(blank(r.category())?"Other":r.category());f.setReferenceNo(t.getOriginalReference());f.setAmount(t.getDebitAmount());f.setPaymentMode(blank(r.paymentMode())?"Bank":r.paymentMode());f.setNotes(blank(r.notes())?t.getOriginalDescription():r.notes());f.setAccountName(r.accountName());f.setBillPath(r.billPath());f.setReconciled(1);f.setCreatedAt(BusinessClock.nowUtcText());f=finance.save(f);String old=t.getStatus();t.setStatus("EXPENSE");txs.save(t);BankReconciliationAllocationEntity al=new BankReconciliationAllocationEntity();al.setStatementTransactionId(t.getId());al.setTargetType("EXPENSE");al.setTargetId(f.getId());al.setAllocatedAmount(t.getDebitAmount());al.setFinanceEntryId(f.getId());al.setCreatedBy(org.example.server.security.CurrentUser.require().username());allocations.save(al);audit(t,"EXPENSE_CREATED","Expense voucher "+f.getVoucherNo()+" created",old,"EXPENSE",r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Expense created from bank statement.","EXPENSE",f.getId());}
 @Transactional public BankReconciliationDtos.OperationResult bankEntry(Long id,BankReconciliationDtos.BankEntryRequest r){var t=reqTxForUpdate(id);ensureProcessable(t);double amount=bankAmount(t);if(amount<=0)throw new IllegalArgumentException("Bank transaction amount must be greater than zero.");boolean credit=n(t.getCreditAmount())>0;FinanceRegisterEntity f=new FinanceRegisterEntity();f.setVoucherNo("BSB-"+id);f.setVoucherType(credit?"BANK DEPOSIT":"BANK WITHDRAWAL");f.setVoucherDate(t.getTransactionDate());f.setCategory(credit?"Deposit":"Withdrawal");f.setReferenceNo(t.getOriginalReference());f.setAmount(amount);f.setPaymentMode(blank(r.paymentMode())?"Bank Statement":r.paymentMode());f.setNotes(blank(r.notes())?t.getOriginalDescription():r.notes());f.setAccountName(blank(r.accountName())?t.getImportBatch().getBankName()+" - "+t.getImportBatch().getBankAccount():r.accountName());f.setReconciled(1);f.setCreatedAt(BusinessClock.nowUtcText());f=finance.save(f);String old=t.getStatus();t.setStatus("MATCHED");txs.save(t);BankReconciliationAllocationEntity al=new BankReconciliationAllocationEntity();al.setStatementTransactionId(t.getId());al.setTargetType("BANK_ENTRY");al.setTargetId(f.getId());al.setAllocatedAmount(amount);al.setFinanceEntryId(f.getId());al.setCreatedBy(org.example.server.security.CurrentUser.require().username());allocations.save(al);audit(t,"BANK_ENTRY_CREATED","Bank entry "+f.getVoucherNo()+" created",old,"MATCHED",r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Bank Entry created from bank statement.","MATCHED",f.getId());}
 @Transactional public BankReconciliationDtos.OperationResult updateNote(Long id,BankReconciliationDtos.NoteRequest r){var t=reqTxForUpdate(id);t.setNotes(r==null?null:r.note());txs.save(t);audit(t,"NOTE_UPDATED",r==null?"":r.note(),t.getStatus(),t.getStatus(),r==null?null:r.user());return new BankReconciliationDtos.OperationResult(true,"Transaction note updated.",t.getStatus(),null);}
 @Transactional public BankReconciliationDtos.OperationResult ignore(Long id,BankReconciliationDtos.IgnoreRequest r){var t=reqTxForUpdate(id);ensureProcessable(t);String old=t.getStatus();t.setStatus("IGNORED");t.setNotes(r==null?null:r.note());txs.save(t);audit(t,"IGNORED",r==null?"Marked intentionally ignored":r.note(),old,"IGNORED",r==null?null:r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction marked as ignored.","IGNORED",null);}
 @Transactional public BankReconciliationDtos.OperationResult review(Long id,BankReconciliationDtos.NoteRequest r){var t=reqTxForUpdate(id);ensureProcessable(t);String old=t.getStatus();t.setStatus("REVIEW");t.setNotes(r==null?"Reviewed by user":r.note());txs.save(t);audit(t,"MARKED_REVIEW","Transaction marked for review",old,"REVIEW",r==null?null:r.user());refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction marked for review.","REVIEW",null);}

 @Transactional public BankReconciliationDtos.OperationResult reverse(Long id,String user){var t=reqTxForUpdate(id);var active=allocations.findByStatementTransactionIdAndReversedAtIsNull(id);if(active.isEmpty()&&"IGNORED".equals(up(t.getStatus()))){String old=t.getStatus();t.setStatus("UNMATCHED");txs.save(t);audit(t,"REOPENED","Ignored transaction returned to reconciliation",old,"UNMATCHED",user);refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Transaction returned to UNMATCHED.","UNMATCHED",null);}if(active.isEmpty())throw new IllegalStateException("No active reconciliation exists for this transaction.");Set<Integer> financeIds=new HashSet<>();for(var a:active){String target=up(a.getTargetType());if(a.getPaymentRecordId()!=null){if("SALE".equals(target)){sales.findByIdForUpdate(a.getTargetId()).ifPresent(x->{double paid=Math.max(0,n(x.getPaidAmount())-n(a.getAllocatedAmount()));x.setPaidAmount(paid);x.setPaymentStatus(paid<=.009?"PENDING":paid+.01>=n(x.getTotalAmount())?"PAID":"PARTIAL");sales.save(x);});payments.deleteById(a.getPaymentRecordId());}else if("PURCHASE".equals(target)){purchases.findByIdForUpdate(a.getTargetId()).ifPresent(x->{double paid=Math.max(0,n(x.getPaidAmount())-n(a.getAllocatedAmount()));x.setPaidAmount(paid);x.setPaymentStatus(paid<=.009?"PENDING":paid+.01>=n(x.getTotalAmount())?"PAID":"PARTIAL");purchases.save(x);});payments.deleteById(a.getPaymentRecordId());}else if(Set.of("SALES_RETURN","PURCHASE_RETURN").contains(target)){String no=jdbc.queryForObject("SELECT return_no FROM return_refund WHERE id=?",String.class,a.getPaymentRecordId());jdbc.update("DELETE FROM return_refund WHERE id=?",a.getPaymentRecordId());if(no!=null&&!no.isBlank())returnService.syncRefundState(no);}}if(a.getFinanceEntryId()!=null)financeIds.add(a.getFinanceEntryId());a.setReversedAt(BusinessClock.nowUtcText());allocations.save(a);}for(Integer fid:financeIds)if(finance.existsById(fid))finance.deleteById(fid);String old=t.getStatus();t.setStatus("UNMATCHED");t.setSuggestedMatchId(null);t.setSuggestedMatchType(null);t.setSuggestedConfidence(null);txs.save(t);audit(t,"REVERSED","Reconciliation reversed",old,"UNMATCHED",user);refreshBatch(t.getImportBatch().getId());return new BankReconciliationDtos.OperationResult(true,"Reconciliation reversed.","UNMATCHED",null);}
 public List<BankReconciliationDtos.AuditDto> audit(Long id){return audits.findByStatementTransactionIdOrderByIdDesc(id).stream().map(a->new BankReconciliationDtos.AuditDto(a.getId(),a.getEventType(),a.getEventDetail(),a.getPreviousStatus(),a.getNewStatus(),a.getPerformedBy(),a.getCreatedAt())).toList();}

 private void applySuggestion(BankStatementTransactionEntity t){String desc=up(t.getOriginalDescription());String holder=compact(t.getImportBatch().getAccountHolder());if(desc.contains("REV-")||desc.startsWith("REV")){t.setStatus("REVIEW");t.setNotes("Possible bank reversal; review before posting.");return;}if(!holder.isBlank()&&compact(desc).contains(holder)){t.setStatus("REVIEW");t.setNotes("Possible transfer involving the statement account holder; verify before posting.");return;}if(desc.contains("CHRG")||desc.contains("CHARGE")){t.setStatus("REVIEW");t.setNotes("Likely bank charge; review and use Move to Expense if appropriate.");return;}var cs=candidatesFor(t);if(!cs.isEmpty()&&cs.get(0).confidence()>=75){var c=cs.get(0);t.setStatus("SUGGESTED");t.setSuggestedMatchType(c.type());t.setSuggestedMatchId(c.id());t.setSuggestedConfidence(c.confidence());}else t.setStatus("UNMATCHED");txs.save(t);}
 private List<BankReconciliationDtos.CandidateDto> candidatesFor(BankStatementTransactionEntity t){
  List<BankReconciliationDtos.CandidateDto> out=new ArrayList<>();double amount=bankAmount(t);
  if(n(t.getCreditAmount())>0){for(var sale:sales.findOpenForBankMatching(amount,PageRequest.of(0,200))){double o=Math.max(0,n(sale.getTotalAmount())-n(sale.getPaidAmount()));out.add(candidate(t,"SALE",sale.getId(),sale.getInvoiceNo(),sale.getCustomer()==null?"":sale.getCustomer().getName(),sale.getInvoiceDate(),n(sale.getTotalAmount()),n(sale.getPaidAmount()),o));}addReturnCandidates(out,t,"PURCHASE RETURN","PURCHASE_RETURN");}
  else{for(var purchase:purchases.findOpenForBankMatching(amount,PageRequest.of(0,200))){double o=Math.max(0,n(purchase.getTotalAmount())-n(purchase.getPaidAmount()));out.add(candidate(t,"PURCHASE",purchase.getId(),purchase.getInvoiceNo(),purchase.getSupplier()==null?"":purchase.getSupplier().getName(),purchase.getInvoiceDate(),n(purchase.getTotalAmount()),n(purchase.getPaidAmount()),o));}addReturnCandidates(out,t,"SALES RETURN","SALES_RETURN");}
  out.sort(Comparator.comparingDouble(BankReconciliationDtos.CandidateDto::confidence).reversed());return out;
 }
 private void addReturnCandidates(List<BankReconciliationDtos.CandidateDto> out,BankStatementTransactionEntity t,String dbType,String candidateType){for(Map<String,Object> r:jdbc.queryForList("SELECT MIN(r.id) id,r.return_no no,MAX(r.return_date) date,MAX(COALESCE(pm.name,'')) party,SUM(r.amount) total,COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0) refunded FROM return_register r LEFT JOIN party_master pm ON pm.id=r.party_id WHERE r.return_type=? AND UPPER(COALESCE(r.status,'PENDING')) NOT IN ('CANCELLED','DELETED') GROUP BY r.return_no HAVING SUM(r.amount)-COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0)>.009 ORDER BY MAX(CASE WHEN COALESCE(r.return_date,'') ~ '^\\d{4}-\\d{2}-\\d{2}$' THEN TO_DATE(r.return_date,'YYYY-MM-DD') WHEN COALESCE(r.return_date,'') ~ '^\\d{2}/\\d{2}/\\d{4}$' THEN TO_DATE(r.return_date,'DD/MM/YYYY') WHEN COALESCE(r.return_date,'') ~ '^\\d{2}-\\d{2}-\\d{4}$' THEN TO_DATE(r.return_date,'DD-MM-YYYY') ELSE NULL END) DESC LIMIT 200",dbType)){int rid=((Number)r.get("id")).intValue();double total=((Number)r.get("total")).doubleValue(),paid=((Number)r.get("refunded")).doubleValue();out.add(candidate(t,candidateType,rid,Objects.toString(r.get("no"),""),Objects.toString(r.get("party"),""),Objects.toString(r.get("date"),""),total,paid,Math.max(0,total-paid)));}}
 private Map<String,Object> returnTarget(int id,String candidateType){String dbType="SALES_RETURN".equals(candidateType)?"SALES RETURN":"PURCHASE RETURN";String returnNo=jdbc.queryForObject("SELECT return_no FROM return_register WHERE id=?",String.class,id);if(returnNo==null||returnNo.isBlank())throw new IllegalArgumentException("Return refund target was not found.");List<String> states=jdbc.query("SELECT COALESCE(status,'PENDING') FROM return_register WHERE return_no=? AND return_type=? FOR UPDATE",(r,i)->r.getString(1),returnNo,dbType);if(states.isEmpty())throw new IllegalArgumentException("Return refund target was not found.");if(states.stream().anyMatch(x->java.util.Set.of("CANCELLED","DELETED").contains(safe(x).trim().toUpperCase(java.util.Locale.ROOT))))throw new IllegalStateException("The selected return is cancelled or deleted and cannot be reconciled.");List<Map<String,Object>> rows=jdbc.queryForList("SELECT MIN(r.id) id,r.return_no no,MAX(r.party_id) party_id,MAX(COALESCE(pm.name,'')) party,SUM(r.amount) total,COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0) refunded FROM return_register r LEFT JOIN party_master pm ON pm.id=r.party_id WHERE r.return_no=? AND r.return_type=? GROUP BY r.return_no",returnNo,dbType);if(rows.isEmpty())throw new IllegalArgumentException("Return refund target was not found.");return rows.getFirst();}
 private BankReconciliationDtos.CandidateDto candidate(BankStatementTransactionEntity t,String type,Integer id,String no,String party,String docDate,double total,double paid,double outstanding){double score=0,amount=bankAmount(t);if(Math.abs(outstanding-amount)<=.01)score+=50;String hay=up(safe(t.getOriginalDescription())+" "+safe(t.getOriginalReference()));if(!blank(no)&&compact(hay).contains(compact(no)))score+=20;String normHay=hay.replaceAll("[^A-Z0-9 ]"," ");if(!blank(party)){String[] tokens=up(party).replaceAll("[^A-Z0-9 ]"," ").split("\\s+");long useful=Arrays.stream(tokens).filter(x->x.length()>=4&&normHay.contains(x)).count();if(useful>0)score+=25;}LocalDate td=date(t.getTransactionDate()),dd=date(docDate);if(td!=null&&dd!=null&&Math.abs(ChronoUnit.DAYS.between(dd,td))<=7)score+=5;return new BankReconciliationDtos.CandidateDto(type,id,no,party,docDate,total,paid,outstanding,Math.min(100,score));}
 private void refreshBatch(Long id){var b=imports.findById(id).orElseThrow();var m=metrics(id);b.setReconciledCount(m.reconciled());b.setReconciliationPercent(m.reconciledPercent());b.setStatus(m.batchStatus());imports.save(b);}
 private BankReconciliationDtos.BatchDto batch(BankStatementImportEntity b){return new BankReconciliationDtos.BatchDto(b.getId(),b.getBankName(),b.getBankAccount(),b.getAccountHolder(),b.getStatementFrom(),b.getStatementTo(),b.getCurrency(),nv(b.getTransactionCount()),n(b.getTotalDebit()),n(b.getTotalCredit()),nv(b.getReconciledCount()),n(b.getReconciliationPercent()),b.getStatus(),b.getSourceFileName(),b.getImportedAt());}
 private List<BankReconciliationDtos.TransactionDto> mapTransactions(List<BankStatementTransactionEntity> rows){
  if(rows==null||rows.isEmpty())return List.of();Set<Long> ids=new HashSet<>();for(var t:rows)ids.add(t.getId());Map<Long,List<BankReconciliationAllocationEntity>> byTx=new HashMap<>();for(var a:allocations.findByStatementTransactionIdInAndReversedAtIsNull(ids))byTx.computeIfAbsent(a.getStatementTransactionId(),ignored->new ArrayList<>()).add(a);
  Set<Integer> saleIds=new HashSet<>(),purchaseIds=new HashSet<>(),returnIds=new HashSet<>();for(var t:rows){for(var a:byTx.getOrDefault(t.getId(),List.of())){String ty=up(a.getTargetType());if("SALE".equals(ty))saleIds.add(a.getTargetId());else if("PURCHASE".equals(ty))purchaseIds.add(a.getTargetId());else if(Set.of("SALES_RETURN","PURCHASE_RETURN").contains(ty))returnIds.add(a.getTargetId());}if(t.getSuggestedMatchId()!=null){String ty=up(t.getSuggestedMatchType());if("SALE".equals(ty))saleIds.add(t.getSuggestedMatchId());else if("PURCHASE".equals(ty))purchaseIds.add(t.getSuggestedMatchId());else if(Set.of("SALES_RETURN","PURCHASE_RETURN").contains(ty))returnIds.add(t.getSuggestedMatchId());}}
  Map<Integer,String> saleNos=new HashMap<>(),purchaseNos=new HashMap<>(),returnNos=new HashMap<>();if(!saleIds.isEmpty())for(var x:sales.findAllById(saleIds))saleNos.put(x.getId(),x.getInvoiceNo());if(!purchaseIds.isEmpty())for(var x:purchases.findAllById(purchaseIds))purchaseNos.put(x.getId(),x.getInvoiceNo());if(!returnIds.isEmpty())for(Map<String,Object> x:jdbc.queryForList("SELECT id,return_no FROM return_register WHERE id IN ("+returnIds.stream().map(x->"?").reduce((a,b)->a+","+b).orElse("0")+")",returnIds.toArray()))returnNos.put(((Number)x.get("id")).intValue(),Objects.toString(x.get("return_no"),""));
  List<BankReconciliationDtos.TransactionDto> out=new ArrayList<>(rows.size());for(var t:rows)out.add(transaction(t,byTx.getOrDefault(t.getId(),List.of()),saleNos,purchaseNos,returnNos));return out;
 }
 private BankReconciliationDtos.TransactionDto transaction(BankStatementTransactionEntity t,List<BankReconciliationAllocationEntity> a,Map<Integer,String> saleNos,Map<Integer,String> purchaseNos,Map<Integer,String> returnNos){
  String link="";Integer financeId=null,targetId=null;String targetType=null,docNo=null;
  List<BankReconciliationDtos.AllocationDto> linked=new ArrayList<>();
  for(var allocation:a){String type=up(allocation.getTargetType());Integer id=allocation.getTargetId();String no=documentNo(type,id,saleNos,purchaseNos,returnNos);linked.add(new BankReconciliationDtos.AllocationDto(allocation.getId(),type,id,no,n(allocation.getAllocatedAmount()),allocation.getPaymentRecordId(),allocation.getFinanceEntryId()));}
  if(!a.isEmpty()){
   var first=a.getFirst();financeId=first.getFinanceEntryId();targetType=up(first.getTargetType());targetId=first.getTargetId();docNo=documentNo(targetType,targetId,saleNos,purchaseNos,returnNos);
   if("EXPENSE".equals(targetType))link="View Expense";else if("BANK_ENTRY".equals(targetType))link="View Bank Entry";else if(a.size()>1)link=a.size()+" linked transactions";else link=docNo;
  }else if(t.getSuggestedMatchId()!=null){targetType=up(t.getSuggestedMatchType());targetId=t.getSuggestedMatchId();docNo=documentNo(targetType,targetId,saleNos,purchaseNos,returnNos);link="Suggested: "+(docNo==null?targetType+" #"+targetId:docNo);}
  return new BankReconciliationDtos.TransactionDto(t.getId(),t.getImportBatch().getId(),t.getSourceRowNumber(),t.getTransactionTimestamp(),t.getTransactionDate(),t.getValueDate(),t.getOriginalDescription(),t.getOriginalReference(),n(t.getDebitAmount()),n(t.getCreditAmount()),n(t.getBalance()),t.getStatus(),t.getSuggestedMatchType(),t.getSuggestedMatchId(),t.getSuggestedConfidence(),link,financeId,targetType,targetId,docNo,List.copyOf(linked));
 }
 private String documentNo(String type,Integer id,Map<Integer,String> saleNos,Map<Integer,String> purchaseNos,Map<Integer,String> returnNos){if(id==null)return null;if("SALE".equals(type))return saleNos.getOrDefault(id,"Sale #"+id);if("PURCHASE".equals(type))return purchaseNos.getOrDefault(id,"Purchase #"+id);if(Set.of("SALES_RETURN","PURCHASE_RETURN").contains(type))return returnNos.getOrDefault(id,"Return #"+id);if("EXPENSE".equals(type))return "Expense #"+id;if("BANK_ENTRY".equals(type))return "Bank Entry #"+id;return type+" #"+id;}

 private BankReconciliationDtos.TransactionDto transaction(BankStatementTransactionEntity t){return mapTransactions(List.of(t)).getFirst();}
 private void audit(BankStatementTransactionEntity t,String event,String detail,String old,String next,String user){BankReconciliationAuditEntity a=new BankReconciliationAuditEntity();a.setStatementTransactionId(t.getId());a.setEventType(event);a.setEventDetail(detail);a.setPreviousStatus(old);a.setNewStatus(next);a.setPerformedBy(org.example.server.security.CurrentUser.require().username());audits.save(a);}
 private BankStatementTransactionEntity reqTx(Long id){return txs.findById(id).orElseThrow(()->new IllegalArgumentException("Bank statement transaction not found."));} private BankStatementTransactionEntity reqTxForUpdate(Long id){return txs.findByIdForUpdate(id).orElseThrow(()->new IllegalArgumentException("Bank statement transaction not found."));} private void ensureProcessable(BankStatementTransactionEntity t){if(RESOLVED.contains(up(t.getStatus())))throw new IllegalStateException("This bank transaction is already resolved. Use Unmatch / Reverse first.");}
 private static double bankAmount(BankStatementTransactionEntity t){return n(t.getCreditAmount())>0?n(t.getCreditAmount()):n(t.getDebitAmount());} private static boolean cancelled(String s){String x=up(s);return x.equals("CANCELLED")||x.equals("DELETED");} private static boolean purchaseLifecycleLocked(String s){String x=up(s);return x.equals("DRAFT")||x.equals("RETURNED")||x.equals("PARTIALLY RETURNED");} private static int nv(Integer v){return v==null?0:v;} private static double n(Number v){return v==null?0:v.doubleValue();} private static String up(String s){return s==null?"":s.trim().toUpperCase(Locale.ROOT);} private static boolean blank(String s){return s==null||s.isBlank();} private static String safe(String s){return s==null?"":s;} private static String compact(String s){return up(s).replaceAll("[^A-Z0-9]","");} private static String fmt(double v){return String.format(Locale.ENGLISH,"%,.2f",v);} private static LocalDate date(String s){if(s==null||s.isBlank())return null;String v=s.trim();try{return LocalDate.parse(v.length()>=10?v.substring(0,10):v);}catch(Exception ignored){}try{return LocalDate.parse(v,java.time.format.DateTimeFormatter.ofPattern("dd/MM/uuuu"));}catch(Exception ignored){}try{return LocalDate.parse(v,java.time.format.DateTimeFormatter.ofPattern("dd-MM-uuuu"));}catch(Exception ignored){return null;}}
}
