package org.example;
import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.example.config.ConfigManager;import org.example.database.DatabaseManager;import org.example.service.ItemSpreadsheetService;
import java.nio.file.*;import java.sql.*;import java.io.*;import java.util.*;
public final class ItemImportSmoke{
 static final String[] H={"Item Code","Description","Category","Brand","Material","Size","Unit","HSN","GST %","Purchase Price","Selling Price","Opening Stock","Minimum Stock","Location","Remarks"};
 public static void main(String[]a)throws Exception{ConfigManager.load();DatabaseManager.initialize();Path dir=Files.createTempDirectory("item-import");ItemSpreadsheetService s=new ItemSpreadsheetService();Path x=dir.resolve("items.xlsx"),l=dir.resolve("items.xls"),c=dir.resolve("items.csv");book(new XSSFWorkbook(),x,"IMP-XLSX");book(new HSSFWorkbook(),l,"IMP-XLS");Files.writeString(c,String.join(",",H)+"\nIMP-CSV,CSV Item,Category,Brand,Material,1,Nos,100,18,10,12,5,1,Main,Imported\n");if(s.importItems(x).imported()!=1||s.importItems(l).imported()!=1||s.importItems(c).imported()!=1)throw new IllegalStateException("Import count mismatch");try(Connection db=DatabaseManager.getConnection();Statement q=db.createStatement();ResultSet r=q.executeQuery("SELECT COUNT(*) FROM item_master WHERE item_code IN ('IMP-XLSX','IMP-XLS','IMP-CSV')")){if(!r.next()||r.getInt(1)!=3)throw new IllegalStateException("Imported items were not persisted");}System.out.println("ITEM_IMPORT_OK xlsx=1 xls=1 csv=1");}
 static void book(Workbook w,Path p,String code)throws Exception{Sheet s=w.createSheet();Row h=s.createRow(0);for(int i=0;i<H.length;i++)h.createCell(i).setCellValue(H[i]);Row r=s.createRow(1);String[]v={code,"Imported Item","Category","Brand","Material","1","Nos","100","18","10","12","5","1","Main","Imported"};for(int i=0;i<v.length;i++)r.createCell(i).setCellValue(v[i]);try(OutputStream o=Files.newOutputStream(p)){w.write(o);}w.close();}
}
