package org.example.server.returns;
import org.example.server.persistence.JpaNativeRepository;import org.example.server.operations.BusinessOperationsService;import org.example.server.security.CurrentUser;import org.example.server.util.BusinessClock;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service public class ReturnService{
 private final JpaNativeRepository jdbc;private final BusinessOperationsService operations;public ReturnService(JpaNativeRepository jdbc,BusinessOperationsService operations){this.jdbc=jdbc;this.operations=operations;}
 @Transactional(readOnly=true) public List<ReturnDtos.Summary> summaries(String type){return jdbc.query("SELECT r.return_no,MAX(r.return_date),MAX(COALESCE(r.invoice_no,'')),MAX(COALESCE(p.name,'')),SUM(r.amount),COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0),MAX(COALESCE(r.reason,'')),CASE WHEN MAX(r.status)='CANCELLED' THEN 'CANCELLED' WHEN COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0)>=SUM(r.amount) AND SUM(r.amount)>0 THEN 'COMPLETED' WHEN COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0)>0 THEN 'PARTIAL' ELSE MAX(COALESCE(r.status,'PENDING')) END,CASE WHEN COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0)>=SUM(r.amount) AND SUM(r.amount)>0 THEN 'REFUNDED' WHEN COALESCE((SELECT SUM(rr.amount) FROM return_refund rr WHERE rr.return_no=r.return_no),0)>0 THEN 'PARTIAL' ELSE 'PENDING' END,MAX(COALESCE(p.email,'')) FROM return_register r LEFT JOIN party_master p ON p.id=r.party_id WHERE r.return_type=? AND UPPER(COALESCE(r.status,'PENDING'))<>'DELETED' GROUP BY r.return_no ORDER BY MAX(CASE WHEN COALESCE(r.return_date,'') ~ '^\\d{4}-\\d{2}-\\d{2}$' THEN TO_DATE(r.return_date,'YYYY-MM-DD') WHEN COALESCE(r.return_date,'') ~ '^\\d{2}/\\d{2}/\\d{4}$' THEN TO_DATE(r.return_date,'DD/MM/YYYY') WHEN COALESCE(r.return_date,'') ~ '^\\d{2}-\\d{2}-\\d{4}$' THEN TO_DATE(r.return_date,'DD-MM-YYYY') ELSE NULL END) DESC,MAX(r.id) DESC",(r,i)->new ReturnDtos.Summary(r.getString(1),String.valueOf(r.getObject(2)),r.getString(3),r.getString(4),r.getDouble(5),r.getDouble(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10)),type);}
 @Transactional(readOnly=true) public Map<String,Double> returned(String type,String invoice){Map<String,Double> out=new HashMap<>();jdbc.query("SELECT item_code,COALESCE(SUM(quantity),0) FROM return_register WHERE return_type=? AND invoice_no=? AND UPPER(COALESCE(status,'PENDING')) NOT IN ('CANCELLED','DELETED') GROUP BY item_code",r->{out.put(r.getString(1),r.getDouble(2));},type,invoice);return out;}
 @Transactional public ReturnDtos.Created create(ReturnDtos.CreateRequest d){if(d==null||d.lines()==null||d.lines().isEmpty())throw new IllegalArgumentException("Select at least one item to return.");String type=d.type()==null?"":d.type().trim().toUpperCase(Locale.ROOT);if(!Set.of("SALES RETURN","PURCHASE RETURN").contains(type))throw new IllegalArgumentException("Return type must be SALES RETURN or PURCHASE RETURN.");if(d.invoiceNo()==null||d.invoiceNo().isBlank())throw new IllegalArgumentException("Invoice number is required.");boolean sales="SALES RETURN".equals(type);String refKey=sales?"REF_SALES_RETURN":"REF_PURCHASE_RETURN",fallback=sales?"SAL-RET-YYYY-XXXX":"PUR-RET-YYYY-XXXX";List<String> existing=jdbc.query("SELECT DISTINCT return_no FROM return_register WHERE return_no IS NOT NULL",(r,i)->r.getString(1));String no=operations.nextConfiguredReference(refKey,fallback,existing);if(sales)requireActiveSaleForReturn(d.invoiceNo());else requirePostedPurchaseForReturn(d.invoiceNo());for(var l:d.lines()){if(l.code()==null||l.code().isBlank())throw new IllegalArgumentException("Return item code is required.");if(!Double.isFinite(l.quantity())||l.quantity()<=0)throw new IllegalArgumentException("Return quantity must be a finite number greater than zero.");if(!Double.isFinite(l.amount())||l.amount()<0)throw new IllegalArgumentException("Return amount must be a finite non-negative number.");double invoiced=invoicedQuantity(sales,d.invoiceNo(),l.code()),already=returnedQuantity(type,d.invoiceNo(),l.code());if(invoiced<=0)throw new IllegalArgumentException("Item "+l.code()+" is not present on invoice "+d.invoiceNo()+".");if(l.quantity()>invoiced-already+.0001)throw new IllegalArgumentException("Return quantity exceeds the remaining invoiced quantity for "+l.code()+".");if(!sales)operations.applyStockDelta(l.code(),-l.quantity(),true);else operations.applyStockDelta(l.code(),l.quantity(),false);String now=BusinessClock.nowUtcText();jdbc.update("INSERT INTO return_register(return_no,return_type,return_date,invoice_no,party_id,item_code,quantity,amount,reason,status,refund_amount,refund_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'PENDING',0,'PENDING',?,?)",no,type,d.returnDate(),d.invoiceNo(),d.partyId(),l.code(),l.quantity(),l.amount(),l.reason(),now,now);}refreshOriginalDocumentStatus(type,d.invoiceNo());return new ReturnDtos.Created(no);}
 @Transactional(readOnly=true) public ReturnDtos.Details details(String no){List<ReturnDtos.Line> lines=jdbc.query("SELECT COALESCE(im.description,r.item_code),r.item_code,r.quantity,COALESCE(im.unit,'Nos'),COALESCE(sl.rate,pl.rate,0),COALESCE(sl.gst_percent,pl.gst_percent,0),r.amount,COALESCE(r.reason,'') FROM return_register r LEFT JOIN item_master im ON im.item_code=r.item_code LEFT JOIN sales_header sh ON sh.invoice_no=r.invoice_no AND r.return_type='SALES RETURN' LEFT JOIN sales_line sl ON sl.sales_id=sh.id AND sl.item_code=r.item_code LEFT JOIN purchase_header ph ON ph.invoice_no=r.invoice_no AND r.return_type='PURCHASE RETURN' LEFT JOIN purchase_line pl ON pl.purchase_id=ph.id AND pl.item_code=r.item_code WHERE r.return_no=? ORDER BY r.id",(r,i)->new ReturnDtos.Line(r.getString(1),r.getString(2),r.getDouble(3),r.getString(4),r.getDouble(5),r.getDouble(6),r.getDouble(7),r.getString(8)),no);if(lines.isEmpty())throw new IllegalArgumentException("Return not found: "+no);Map<String,Object> h=jdbc.queryForMap("SELECT MAX(r.return_no) no,MAX(r.return_date) date,MAX(COALESCE(r.invoice_no,'')) invoice,MAX(COALESCE(pm.name,'')) party,MAX(r.return_type) type,MAX(COALESCE(ph.payment_terms,'')) terms,MAX(COALESCE(ph.currency,'INR - Indian Rupee')) currency,MAX(COALESCE(r.created_at::text,'')) created,MAX(COALESCE(r.updated_at::text,'')) updated,MAX(COALESCE(r.attachment_path,'')) attachment,MAX(COALESCE(r.notes,'')) notes,SUM(r.amount) total,MAX(COALESCE(r.status,'PENDING')) raw_status FROM return_register r LEFT JOIN party_master pm ON pm.id=r.party_id LEFT JOIN purchase_header ph ON ph.invoice_no=r.invoice_no WHERE r.return_no=?",no);double total=n(h.get("total")),refund=refundTotal(no);String raw=Objects.toString(h.get("raw_status"),"PENDING"),refundStatus=refund<=.0001?"PENDING":refund+.0001>=total?"REFUNDED":"PARTIAL",status="CANCELLED".equalsIgnoreCase(raw)?"CANCELLED":"REFUNDED".equals(refundStatus)?"COMPLETED":"PARTIAL".equals(refundStatus)?"PARTIAL":raw;return new ReturnDtos.Details(no,Objects.toString(h.get("date"),""),Objects.toString(h.get("invoice"),""),Objects.toString(h.get("party"),""),Objects.toString(h.get("type"),""),Objects.toString(h.get("terms"),""),Objects.toString(h.get("currency"),"INR - Indian Rupee"),Objects.toString(h.get("created"),""),Objects.toString(h.get("updated"),""),Objects.toString(h.get("attachment"),""),Objects.toString(h.get("notes"),""),total,refund,status,refundStatus,lines);}
 @Transactional public void update(String no,String field,String value){if(!Set.of("reason","notes").contains(field))throw new IllegalArgumentException("Return status is lifecycle-managed and cannot be edited directly.");jdbc.update("UPDATE return_register SET "+field+"=?,updated_at=? WHERE return_no=?",value,BusinessClock.nowUtcText(),no);}
 @Transactional public void refund(String no,double amount){recordRefund(no,new ReturnDtos.RefundCreateRequest(BusinessClock.today().toString(),amount,"Legacy Refund","","","","Recorded from legacy refund action","PARTIAL",CurrentUser.require().username()));}
 @Transactional(readOnly=true) public List<ReturnDtos.RefundRow> refunds(String no){requireAccess(no);return jdbc.query("SELECT id,refund_date,COALESCE(reference_no,''),COALESCE(payment_mode,''),COALESCE(bank_account,''),amount,COALESCE(refunded_party,''),CASE WHEN UPPER(COALESCE(refund_type,''))='BANK_RECONCILIATION' THEN 'RECONCILED' ELSE 'RECORDED' END,COALESCE(notes,''),COALESCE(attachment_path,''),COALESCE(refund_type,'PARTIAL') FROM return_refund WHERE return_no=? ORDER BY refund_date DESC,id DESC",(r,i)->new ReturnDtos.RefundRow(r.getInt(1),String.valueOf(r.getObject(2)),r.getString(3),r.getString(4),r.getString(5),r.getDouble(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11)),no);}
 @Transactional public int recordRefund(String no,ReturnDtos.RefundCreateRequest d){requireAccess(no);requireRefundEligible(no);if(d==null)throw new IllegalArgumentException("Refund details are required.");double total=total(no),already=refundTotal(no),remaining=Math.max(0,total-already);if(!Double.isFinite(d.amount())||d.amount()<=0||d.amount()>remaining+.0001)throw new IllegalArgumentException("Refund amount must be greater than zero and no more than the remaining refund balance of "+String.format(java.util.Locale.ROOT,"%.2f",remaining)+".");java.time.LocalDate date;try{date=java.time.LocalDate.parse(d.date());}catch(Exception e){throw new IllegalArgumentException("Refund date must use YYYY-MM-DD.");}String mode=d.mode()==null?"":d.mode().trim();if(mode.isBlank())throw new IllegalArgumentException("Refund payment mode is required.");Integer id=jdbc.queryForObject("INSERT INTO return_refund(return_no,refund_date,amount,payment_mode,reference_no,bank_account,refunded_party,notes,refund_type,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING id",Integer.class,no,date,d.amount(),mode,clean(d.reference()),clean(d.bankAccount()),clean(d.refundedParty()),clean(d.notes()),clean(d.refundType())==null?"PARTIAL":clean(d.refundType()),clean(d.createdBy())==null?CurrentUser.require().username():clean(d.createdBy()),BusinessClock.nowUtcText());syncRefundState(no);if(id==null)throw new IllegalStateException("Refund id was not returned after saving.");return id;}
 @Transactional public void syncRefundState(String no){double total=total(no),paid=refundTotal(no);String rs=paid<=.0001?"PENDING":paid+.0001>=total?"REFUNDED":"PARTIAL",status="REFUNDED".equals(rs)?"COMPLETED":"PARTIAL".equals(rs)?"PARTIAL":"PENDING";String current=jdbc.queryForObject("SELECT MAX(COALESCE(status,'PENDING')) FROM return_register WHERE return_no=?",String.class,no);if("CANCELLED".equalsIgnoreCase(current))status="CANCELLED";jdbc.update("UPDATE return_register SET refund_amount=0,refund_status=?,status=?,updated_at=? WHERE return_no=?",rs,status,BusinessClock.nowUtcText(),no);if(paid>.0001)jdbc.update("UPDATE return_register SET refund_amount=? WHERE id=(SELECT MIN(id) FROM return_register WHERE return_no=?)",paid,no);}
 private double refundTotal(String no){Double d=jdbc.queryForObject("SELECT COALESCE(SUM(amount),0) FROM return_refund WHERE return_no=?",Double.class,no);return d==null?0:d;}
 private String clean(String x){return x==null||x.isBlank()?null:x.trim();}
 @Transactional public void delete(String no,boolean ignoredSalesFlag){requireAccess(no);assertUnrefunded(no);String state=currentStateForUpdate(no);if("DELETED".equals(state))return;ReturnOrigin origin=origin(no);if(!"CANCELLED".equals(state))reverse(no,"SALES RETURN".equalsIgnoreCase(origin.type()));jdbc.update("UPDATE return_register SET status='DELETED',updated_at=? WHERE return_no=?",BusinessClock.nowUtcText(),no);refreshOriginalDocumentStatus(origin.type(),origin.invoice());}
 @Transactional public void cancel(String no,boolean ignoredSalesFlag){requireAccess(no);assertUnrefunded(no);String state=currentStateForUpdate(no);if("DELETED".equals(state))throw new IllegalStateException("Deleted returns cannot be cancelled.");if("CANCELLED".equals(state))throw new IllegalStateException("This return is already cancelled.");ReturnOrigin origin=origin(no);reverse(no,"SALES RETURN".equalsIgnoreCase(origin.type()));jdbc.update("UPDATE return_register SET status='CANCELLED',updated_at=? WHERE return_no=?",BusinessClock.nowUtcText(),no);refreshOriginalDocumentStatus(origin.type(),origin.invoice());}
 private void assertUnrefunded(String no){Long cnt=jdbc.queryForObject("SELECT COUNT(*) FROM return_register WHERE return_no=?",Long.class,no);if(cnt==null||cnt==0)throw new IllegalStateException("Return "+no+" was not found.");if(refundTotal(no)>.0001)throw new IllegalStateException("A refunded or partially refunded return cannot be deleted or cancelled because it would corrupt accounting history.");}
 private double total(String no){Double d=jdbc.queryForObject("SELECT COALESCE(SUM(amount),0) FROM return_register WHERE return_no=?",Double.class,no);if(d==null||d<=0)throw new IllegalStateException("Return "+no+" was not found.");return d;}
 private void reverse(String no,boolean sales){for(Map<String,Object> r:jdbc.queryForList("SELECT item_code,quantity FROM return_register WHERE return_no=?",no)){double q=n(r.get("quantity"));String code=Objects.toString(r.get("item_code"),"");operations.applyStockDelta(code,sales?-q:q,sales);}}
 private String currentStateForUpdate(String no){List<String> rows=jdbc.query("SELECT COALESCE(status,'PENDING') FROM return_register WHERE return_no=? FOR UPDATE",(r,i)->r.getString(1),no);if(rows.isEmpty())throw new IllegalArgumentException("Return not found: "+no);return rows.stream().map(ReturnService::up).filter(x->!x.isBlank()).findFirst().orElse("PENDING");}
 private double recordedPayments(String type,int id){Double value=jdbc.queryForObject("SELECT COALESCE(SUM(amount),0) FROM payment_record WHERE UPPER(document_type)=? AND document_id=?",Double.class,type,id);return value==null?0:value;}
 private static String up(Object x){return Objects.toString(x,"").trim().toUpperCase(Locale.ROOT);}
 private void requireActiveSaleForReturn(String invoice){List<Object[]> rows=jdbc.query("SELECT id,COALESCE(document_status,''),COALESCE(total_amount,0),COALESCE(paid_amount,0),COALESCE(payment_status,'') FROM sales_header WHERE invoice_no=? FOR UPDATE",(r,i)->new Object[]{r.getInt(1),r.getString(2),r.getDouble(3),r.getDouble(4),r.getString(5)},invoice);if(rows.isEmpty())throw new IllegalArgumentException("Sales invoice not found: "+invoice);Object[] row=rows.getFirst();String status=up(row[1]);if(Set.of("DELETED","CANCELLED","RETURNED","PENDING APPROVAL","REJECTED").contains(status))throw new IllegalStateException("Only an approved active Sale can create a Sales Return.");int id=((Number)row[0]).intValue();double total=n(row[2]),cached=n(row[3]),recorded=recordedPayments("SALE",id),effective=Math.max(cached,recorded);String payment=up(row[4]);if(total<=.0001||(effective+.0001<total&&!Set.of("PAID","SETTLED").contains(payment)))throw new IllegalStateException("Sales Return is available only after the source Sale is fully paid.");}
 private void requirePostedPurchaseForReturn(String invoice){List<Object[]> rows=jdbc.query("SELECT id,COALESCE(document_status,''),COALESCE(inventory_posted,false),COALESCE(total_amount,0),COALESCE(paid_amount,0),COALESCE(payment_status,'') FROM purchase_header WHERE invoice_no=? FOR UPDATE",(r,i)->new Object[]{r.getInt(1),r.getString(2),Boolean.TRUE.equals(r.getObject(3)),r.getDouble(4),r.getDouble(5),r.getString(6)},invoice);if(rows.isEmpty())throw new IllegalArgumentException("Purchase invoice not found: "+invoice);Object[] row=rows.getFirst();String status=up(row[1]);boolean posted=Boolean.TRUE.equals(row[2]);if(!posted||Set.of("DRAFT","DELETED","CANCELLED","RETURNED","PENDING APPROVAL","REJECTED").contains(status))throw new IllegalStateException("Only an approved active posted Purchase can create a Purchase Return.");int id=((Number)row[0]).intValue();double total=n(row[3]),cached=n(row[4]),recorded=recordedPayments("PURCHASE",id),effective=Math.max(cached,recorded);String payment=up(row[5]);if(total<=.0001||(effective+.0001<total&&!Set.of("PAID","SETTLED").contains(payment)))throw new IllegalStateException("Purchase Return is available only after the source Purchase is fully paid.");}
 private double invoicedQuantity(boolean sales,String invoice,String code){String sql=sales?"SELECT COALESCE(SUM(l.quantity),0) FROM sales_line l JOIN sales_header h ON h.id=l.sales_id WHERE h.invoice_no=? AND l.item_code=?":"SELECT COALESCE(SUM(l.quantity),0) FROM purchase_line l JOIN purchase_header h ON h.id=l.purchase_id WHERE h.invoice_no=? AND l.item_code=?";Double value=jdbc.queryForObject(sql,Double.class,invoice,code);return value==null?0:value;}
 private void requireRefundEligible(String no){List<String> states=jdbc.query("SELECT COALESCE(status,'PENDING') FROM return_register WHERE return_no=? FOR UPDATE",(r,i)->r.getString(1),no);if(states.isEmpty())throw new IllegalArgumentException("Return not found: "+no);if(states.stream().anyMatch(x->Set.of("CANCELLED","DELETED").contains(up(x))))throw new IllegalStateException("Cancelled or deleted returns cannot receive refunds.");}
 private double returnedQuantity(String type,String invoice,String code){Double value=jdbc.queryForObject("SELECT COALESCE(SUM(quantity),0) FROM return_register WHERE return_type=? AND invoice_no=? AND item_code=? AND UPPER(COALESCE(status,'PENDING')) NOT IN ('CANCELLED','DELETED')",Double.class,type,invoice,code);return value==null?0:value;}
 private ReturnOrigin origin(String no){Map<String,Object> row=jdbc.queryForMap("SELECT MAX(return_type) type,MAX(invoice_no) invoice FROM return_register WHERE return_no=?",no);String type=Objects.toString(row.get("type"),"");String invoice=Objects.toString(row.get("invoice"),"");if(type.isBlank()||invoice.isBlank())throw new IllegalArgumentException("Return not found: "+no);return new ReturnOrigin(type,invoice);}
 private void refreshOriginalDocumentStatus(String type,String invoice){
  boolean sales="SALES RETURN".equalsIgnoreCase(type);
  String table=sales?"sales_header":"purchase_header", lineTable=sales?"sales_line":"purchase_line", idColumn=sales?"sales_id":"purchase_id";
  Map<String,Object> header=jdbc.queryForMap("SELECT id,COALESCE(document_status,'') status"+(sales?",COALESCE(total_amount,0) total,COALESCE(paid_amount,0) paid":"")+" FROM "+table+" WHERE invoice_no=? FOR UPDATE",invoice);
  String current=Objects.toString(header.get("status"),"").trim().toUpperCase(Locale.ROOT);
  if(Set.of("CANCELLED","DELETED").contains(current))return;
  int documentId=((Number)header.get("id")).intValue();
  Double originalValue=jdbc.queryForObject("SELECT COALESCE(SUM(quantity),0) FROM "+lineTable+" WHERE "+idColumn+"=?",Double.class,documentId);
  Double returnedValue=jdbc.queryForObject("SELECT COALESCE(SUM(quantity),0) FROM return_register WHERE return_type=? AND invoice_no=? AND UPPER(COALESCE(status,'PENDING')) NOT IN ('CANCELLED','DELETED')",Double.class,type,invoice);
  double original=originalValue==null?0:originalValue, returned=returnedValue==null?0:returnedValue;
  String next;
  if(returned>.0001){next=original>0&&returned+0.0001>=original?"RETURNED":"PARTIALLY RETURNED";}
  else if(sales){double total=n(header.get("total")),paid=n(header.get("paid"));next=total>0&&paid+0.0001>=total?"COMPLETED":paid>.0001?"IN PROGRESS":"PENDING";}
  else{next="COMPLETED";}
  jdbc.update("UPDATE "+table+" SET document_status=?,updated_at=? WHERE invoice_no=?",next,BusinessClock.nowUtcText(),invoice);
 }
 private record ReturnOrigin(String type,String invoice){}
 public void requireTypeAccess(String type){if(CurrentUser.isSales()&&!"SALES RETURN".equalsIgnoreCase(type==null?"":type.trim()))throw new SecurityException("Purchase returns require Manager or Admin access");}
 public void requireAccess(String no){if(CurrentUser.isSales()&&!isSalesReturn(no))throw new SecurityException("Purchase returns require Manager or Admin access");}
 private boolean isSalesReturn(String no){String type=jdbc.queryForObject("SELECT MAX(return_type) FROM return_register WHERE return_no=?",String.class,no);if(type==null||type.isBlank())throw new IllegalArgumentException("Return not found: "+no);return "SALES RETURN".equalsIgnoreCase(type);}
 private double n(Object x){return x instanceof Number v?v.doubleValue():0;}
}
