from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def text(rel): return (ROOT/rel).read_text(encoding='utf-8')
def req(ok,msg):
    if not ok: raise SystemExit('FAIL: '+msg)
    print('PASS:',msg)
policy=text('server/src/main/java/org/example/server/insights/BusinessKpiPolicy.java')
ins=text('server/src/main/java/org/example/server/insights/InsightsService.java')
cash=text('server/src/main/java/org/example/server/insights/CashPositionService.java')
ops=text('server/src/main/java/org/example/server/operations/BusinessOperationsService.java')
quote=text('server/src/main/java/org/example/server/quotation/QuotationService.java')
returns=text('server/src/main/java/org/example/server/returns/ReturnService.java')
bank=text('desktop/src/main/java/org/example/controller/BankStatementController.java')
record=text('desktop/src/main/java/org/example/controller/RecordPaymentController.java')
purchasepay=text('desktop/src/main/java/org/example/controller/PurchasePaymentController.java')
refund=text('desktop/src/main/java/org/example/controller/ReturnRefundController.java')
qctrl=text('desktop/src/main/java/org/example/controller/QuotationController.java')
reports=text('desktop/src/main/java/org/example/controller/ReportsController.java')
dashboard=text('desktop/src/main/java/org/example/controller/DashboardHomeController.java')
bankexpense=text('desktop/src/main/java/org/example/controller/BankExpenseController.java')
lookup=text('desktop/src/main/java/org/example/service/LookupService.java')
runtime=text('shared/src/main/java/org/example/shared/RuntimeContract.java')
req('APP_VERSION = "9.0.28"' in runtime and 'BUILD_REVISION = "9.0.28"' in runtime,'v9.0.28 runtime identity')
req('salesActive' in policy and 'purchasesActive' in policy and 'effectivePaid' in policy and 'outstanding' in policy,'one canonical KPI SQL policy')
req('BusinessKpiPolicy.salesActive' in ins and 'BusinessKpiPolicy.purchasesActive' in ins and 'BusinessKpiPolicy.salesActive' in ops and 'BusinessKpiPolicy.purchasesActive' in ops,'Dashboard/Reports/register KPI status rules share policy')
req('bank_account' in cash and 'account_number' not in cash,'cash opening-balance query uses actual bank_account schema')
req('cashPosition::cashPosition' in ins and 'cashPosition.cashPosition()' in ops,'Dashboard and Finance share one Cash Position calculation')
req("UPPER(document_type)='SALE'" in cash and "UPPER(document_type)='PURCHASE'" in cash and 'rounding_adjustment' in cash,'cash position includes receipts/payments/refunds consistently')
req('metrics(joins,where.toString(),base)' in quote and "UPPER(TRIM(q.status))" in quote,'Quotation KPIs respect current filters with normalized status')
req('FROM s" + filter' in returns and 'baseArgs' in returns,'Return KPIs use the same current register filters')
req('getByCategoryCode("BANK_ACCOUNT")' in bank and 'configureBankAccountMaster();\n        org.example.util.OperationalUiSupport.focusSearch' in bank,'Bank Statement refreshes canonical BANK_ACCOUNT on every screen show')
req('configureBankAccountMaster();\n        FileChooser' in bank,'Bank Statement import refreshes Bank Account immediately before use')
req('loadPaymentLookupsAsync(); loadSelectedInvoice();' in record and 'mode.setOnShowing(e->loadPaymentLookupsAsync())' in record,'Sales payment Master lookups refresh on reuse/open')
req('loadPaymentLookupsAsync(); if (reusedFromCache)' in purchasepay and 'mode.setOnShowing(e->loadPaymentLookupsAsync())' in purchasepay,'Purchase payment Master lookups refresh on reuse/open')
req('refreshMasterLookups();' in refund and 'getByCategoryCode("BANK_ACCOUNT")' in refund and 'setOnShowing(e->refreshMasterLookups())' in refund,'Return Refund Master lookups refresh on open')
req('refreshSourceFilter();' in qctrl and 'cmbSource.setOnShowing(e->refreshSourceFilter())' in qctrl,'Quotation Source register filter refreshes from Master')
req('loadFiltersAsync(); if(!loadRequested' in reports and 'if(selected!=null&&box.getItems().contains(selected))' in reports,'Reports reload linked filters while preserving selection')
req('ScreenRefreshPolicy.invalidateAll()' in lookup,'local Master lookup mutations invalidate cached screen freshness')
req('implements ScreenLifecycle' in dashboard and 'if (reusedFromCache) reload();' in dashboard,'Dashboard reloads current KPIs when cached screen is shown again')
req('paymentMode.setOnShowing' in bankexpense and 'bankAccount.setOnShowing' in bankexpense and 'expenseAccount.setOnShowing' in bankexpense,'Bank/Expense Master-backed dropdowns refresh when opened')
req('account_number' not in ins and 'account_number' not in ops,'stale account_number SQL removed from KPI services')
print('PASS: v9.0.28 KPI and Master refresh audit complete')
