from pathlib import Path
root=Path(__file__).resolve().parents[1]
def text(p): return (root/p).read_text(encoding='utf-8',errors='ignore')
def req(ok,msg):
    if not ok: raise SystemExit('FAIL: '+msg)
ref=text('shared/src/main/java/org/example/shared/ReferenceFormatRules.java')
ops=text('server/src/main/java/org/example/server/operations/BusinessOperationsService.java')
master=text('server/src/main/java/org/example/server/master/MasterDataService.java')
item=text('desktop/src/main/java/org/example/controller/ItemDialogController.java')
items=text('desktop/src/main/java/org/example/controller/ItemMasterController.java')
imp=text('desktop/src/main/java/org/example/controller/ImportController.java')
qsvc=text('server/src/main/java/org/example/server/quotation/QuotationService.java')
qctl=text('server/src/main/java/org/example/server/quotation/QuotationController.java')
qapi=text('desktop/src/main/java/org/example/api/quotation/QuotationApiClient.java')
qedit=text('desktop/src/main/java/org/example/controller/QuotationEditorController.java')
qreg=text('desktop/src/main/java/org/example/controller/QuotationController.java')
runner=text('server/src/main/java/org/example/server/runtime/SecurityFinancialMigrationRunner.java')
mig=text('server/src/main/resources/db/migration/V9_0_15__reference_and_quotation_source_hardening.sql')
runtime=text('shared/src/main/java/org/example/shared/RuntimeContract.java')
props=text('server/src/main/resources/application.properties')
pom=text('pom.xml')
app=text('desktop/src/main/resources/app-version.properties')
update=text('desktop/src/main/java/org/example/update/UpdateService.java')
req('append(",}")' in ref, 'reference regex must accept sequence digits beyond configured X minimum width')
req('Reference sequence exhausted' not in ops and 'capacity=' not in ops, 'configured allocator must not impose X-width capacity')
req('seq.length()>width' not in ops, 'existing reference scan must accept expanded numeric sequences')
req('minimum zero-padding' in master, 'Master Data help must describe expandable X padding')
req('savedResult=saved' in item and 'Item saved but notification could not be created' in item, 'Item save must survive notification failure and return a parent-screen result')
req('ToastManager.success(tableItems' in items and 'selectSavedItem(saved.getItemCode())' in items, 'Item Master must show persistent success and select the saved record')
req('Create new • Skip existing posted documents' in imp and 'isFixedImportPolicy' in imp and 'selectedImportMode()' in imp, 'Import Step 4 must be module-aware')
req('cmbImportMode.setDisable(running || isFixedImportPolicy' in imp, 'Import mode must lock while import runs')
req('sourceChoices()' in qsvc and 'activeQuotationSources()' in qsvc and 'QUOTATION_SOURCE_CODE="QUOTATION_SOURCE"' in qsvc and 'masterData.valuesByCategoryCode(QUOTATION_SOURCE_CODE)' in qsvc, 'Quotation service must expose canonical Master-driven Source choices')
req('lookup_master l' not in qsvc[qsvc.find('private List<String> activeQuotationSources'):qsvc.find('@Transactional(readOnly=true)\n    public List<QuotationDtos.ItemChoiceDto>')], 'Quotation Source runtime lookup must not maintain duplicate SQL authority')
req('@GetMapping("/sources")' in qctl and 'public List<String> sources()' in qapi, 'Backward-compatible Quotation Source API endpoint must remain available')
req('lookupService.getValuesByCategoryCode("QUOTATION_SOURCE")' in qedit, 'Quotation editor must load Source through generic Master LookupService')
req('lookupService.getValuesByCategoryCode("QUOTATION_SOURCE")' in qreg, 'Quotation register Source filter must use generic Master LookupService')
req('V9_0_15__reference_and_quotation_source_hardening' in runner and 'QUOTATION_SOURCE' in mig, 'v9.0.18 compatibility migration must be registered')
req('APP_VERSION = "9.0.47"' in runtime and 'BUILD_REVISION = "9.0.47"' in runtime, 'runtime identity must be 9.0.18')
req('dse.app.version=9.0.47' in props and 'dse.build.revision=9.0.47' in props, 'server identity must be 9.0.18')
req('<version>9.0.47</version>' in pom and '<dse.phase>9.0.47</dse.phase>' in pom, 'Maven identity must be 9.0.18')
req('version=9.0.47' in app and 'DEFAULT_VERSION="9.0.47"' in update, 'desktop/update identity must be 9.0.18')
print('PASS: DSE ERP 9.0.18 reference/item/import/quotation-source contract')
