from pathlib import Path
root=Path(__file__).resolve().parents[1]
def text(path): return (root/path).read_text(encoding="utf-8")
def req(ok,msg):
    if not ok: raise SystemExit("FAIL: "+msg)
    print("PASS:",msg)

ret=text(Path("server/src/main/java/org/example/server/returns/ReturnService.java"))
ctrl=text(Path("server/src/main/java/org/example/server/returns/ReturnController.java"))
dtos=text(Path("server/src/main/java/org/example/server/returns/ReturnDtos.java"))
ops=text(Path("server/src/main/java/org/example/server/operations/BusinessOperationsService.java"))
mig=text(Path("server/src/main/resources/db/migration/V9_0_24__return_lifecycle_authority.sql"))
runner=text(Path("server/src/main/java/org/example/server/runtime/SecurityFinancialMigrationRunner.java"))
sales=text(Path("desktop/src/main/java/org/example/controller/SalesListController.java"))
purchase=text(Path("desktop/src/main/java/org/example/controller/PurchaseListController.java"))
sr=text(Path("desktop/src/main/java/org/example/controller/SalesReturnsController.java"))
pr=text(Path("desktop/src/main/java/org/example/controller/PurchaseReturnsController.java"))
sm=text(Path("desktop/src/main/java/org/example/model/Sales.java"))
pm=text(Path("desktop/src/main/java/org/example/model/Purchase.java"))
bank=text(Path("server/src/main/java/org/example/server/reconciliation/BankReconciliationService.java"))
props=text(Path("server/src/main/resources/application.properties"))

req("dse.app.version=9.0.34" in props,"v9.0.34 runtime identity")
req("dse.return.settlement-days=7" in props,"server-owned Return settlement due policy")
req("'PENDING APPROVAL'" in ret and "no stock/accounting movement until Admin approves" in ret,"Return creation is Pending Approval with no early stock posting")
req("public void approve(String no)" in ret and "postReturnStock(no, sales)" in ret,"Admin Return approval posts stock")
req("public void reject(String no, String reason)" in ret and "status='REJECTED'" in ret,"Return rejection is lifecycle-managed")
req("recordRefund" in ret and 'if (!"APPROVED".equals(state))' in ret,"refund/settlement blocked until Return approval")
req("refreshOriginalDocumentStatus" not in ret,"Return never rewrites original Sale/Purchase document status")
req("Sales Return is available only after the source Sale is fully paid" in ret and "Purchase Return is available only after the source Purchase is fully paid" in ret,"Return allowed only from fully-paid originals")
req("RETURN PENDING" in ret and "RETURN PARTIAL" in ret and "RETURN PAID" in ret,"approved Return settlement overlay states")
req('GetMapping("/settlements")' in ctrl and 'PostMapping("/{no}/approve")' in ctrl and 'PostMapping("/{no}/reject")' in ctrl,"Return REST lifecycle endpoints")
req("record Settlement(" in dtos,"Return settlement DTO")
req("V9_0_24__return_lifecycle_authority.sql" in runner,"v9.0.34 lifecycle migration registered")
req("document_status='APPROVED'" in mig and "settlement_due_date" in mig,"legacy lifecycle normalized without rewriting accounting history")
req('currentPaymentStatusSql' in ops and 'RETURN PAID' in ops and 'RETURN PARTIAL' in ops and 'RETURN PENDING' in ops,"server register filtering understands Return settlement state")
req('colPaymentStatus' in sales and 'colPaymentStatus' in purchase,"Sales/Purchase Registers show separate Document and Payment status")
for content,name in ((sales,"Sales"),(purchase,"Purchase")):
    req('"PENDING APPROVAL","APPROVED","REJECTED","CANCELLED"' in content,f"{name} Document Status filter uses lifecycle-only states")
    req('"RETURN PENDING","RETURN PARTIAL","RETURN PAID"' in content,f"{name} Payment Status filter includes Return states")
    req('"APPROVED".equals(document)' in content and "getBasePaymentStatus" in content,f"{name} Return UI requires Approved + base Paid")
req("applyReturnSettlement" in sm and "basePaymentStatus" in sm and "returnPendingAmount" in sm,"Sales model preserves original payment history under Return overlay")
req("applyReturnSettlement" in pm and "basePaymentStatus" in pm and "returnPendingAmount" in pm,"Purchase model preserves original payment history under Return overlay")
for content,name in ((sr,"Sales Return"),(pr,"Purchase Return")):
    req('"PENDING APPROVAL"' in content and '"APPROVED"' in content and '"REJECTED"' in content,f"{name} Register uses approval lifecycle")
    req("approveReturn" in content and "rejectReturn" in content,f"{name} Admin approve/reject actions")
    req("Refund/settlement can be recorded only after Admin approves the Return" in content,f"{name} refund UI approval gate")
req("UPPER(COALESCE(r.status,''))='APPROVED'" in bank,"Bank reconciliation offers only approved Return settlements")
print("PASS: DSE ERP v9.0.34 Return lifecycle contract")
