param([Parameter(Mandatory=$true)][string]$Workspace,[Parameter(Mandatory=$true)][string]$ServerUrl,[Parameter(Mandatory=$true)][string]$AdminToken,[Parameter(Mandatory=$true)][string]$LocalDatabaseUrl,[Parameter(Mandatory=$true)][string]$LocalDatabaseUser,[string]$PostgresHome='', [switch]$Finalize)
$ErrorActionPreference='Stop';$ServerUrl=$ServerUrl.TrimEnd('/');$health=Invoke-RestMethod -Uri "$ServerUrl/api/runtime/health" -Method Get;if(!$health.ready){throw 'Company server is not READY'};if($health.version -ne '9.0.77'){throw "Company server must be 9.0.77; found $($health.version)"}
$config=Join-Path $Workspace 'Configuration\config.properties';if(!(Test-Path -LiteralPath $config)){throw "Workspace configuration not found: $config"}
$headers=@{Authorization="Bearer $AdminToken"}
function Put-Setting([string]$Key,[string]$Value){$json=@{value=$Value}|ConvertTo-Json -Compress;Invoke-RestMethod -Uri "$ServerUrl/api/support/settings/$([uri]::EscapeDataString($Key))" -Method Put -Headers $headers -ContentType application/json -Body $json|Out-Null}
function Put-Resource([string]$Type,[string]$Key,[string]$File){$uri="$ServerUrl/api/authority/resources/$Type/$([uri]::EscapeDataString($Key))?filename=$([uri]::EscapeDataString((Split-Path $File -Leaf)))";Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -ContentType application/octet-stream -InFile $File|Out-Null}
if($Finalize){$backup=Join-Path $Workspace 'Backups\promotion-local-safety.pgbackup';if(!(Test-Path -LiteralPath $backup)){throw 'Promotion safety backup is missing; run the staging phase first'}
 $properties=@{};Get-Content -LiteralPath $config|Where-Object {$_ -match '^[^#!][^=]*='}|ForEach-Object {$k,$v=$_.Split('=',2);$properties[$k.Trim()]=$v};foreach($entry in $properties.GetEnumerator()){if($entry.Key -match '^(company\.|payment\.|invoice\.|business\.|tax\.|reference\.)'){Put-Setting $entry.Key $entry.Value}}
 foreach($assetKey in @('company.logoPath','company.signaturePath','payment.qrImagePath')){if($properties[$assetKey] -and (Test-Path -LiteralPath $properties[$assetKey])){Put-Resource 'BUSINESS_ASSET' $assetKey $properties[$assetKey];Put-Setting $assetKey "server-resource:$assetKey"}}
 $templateRoot=Join-Path $Workspace 'Templates\DocumentStudio';$tempArchives=@();try{foreach($spec in @(@('PDF_TEMPLATE',$templateRoot),@('EXCEL_TEMPLATE',(Join-Path $templateRoot 'Excel')))){if(!(Test-Path -LiteralPath $spec[1])){continue};Get-ChildItem -LiteralPath $spec[1] -Directory|Where-Object {Test-Path -LiteralPath (Join-Path $_.FullName 'template.json')}|ForEach-Object {$archive=Join-Path ([IO.Path]::GetTempPath()) ("dse-promotion-"+[guid]::NewGuid()+'.zip');Compress-Archive -Path (Join-Path $_.FullName '*') -DestinationPath $archive -Force;$tempArchives+=$archive;Put-Resource $spec[0] $_.Name $archive}}}finally{foreach($archive in $tempArchives){Remove-Item -LiteralPath $archive -Force -ErrorAction SilentlyContinue}}
 $lines=Get-Content -LiteralPath $config | Where-Object {$_ -notmatch '^(deployment.mode|server.baseUrl)='};$lines+=@('deployment.mode=SHARED_CLIENT',"server.baseUrl=$ServerUrl");$temp="$config.9.0.77.tmp";Set-Content -LiteralPath $temp -Value $lines -Encoding ISO8859-1;Move-Item -LiteralPath $temp -Destination $config -Force;Write-Host 'Promotion finalized. Server settings, assets and templates were published. Restart DSE ERP and sign in to the company server.';exit 0}
$backupFolder=Join-Path $Workspace 'Backups';New-Item -ItemType Directory -Force -Path $backupFolder|Out-Null;$backup=Join-Path $backupFolder 'promotion-local-safety.pgbackup';$pgDump=if($PostgresHome){Join-Path $PostgresHome 'bin\pg_dump.exe'}else{'pg_dump'};& $pgDump '--format=custom' '--no-owner' '--no-privileges' "--username=$LocalDatabaseUser" "--file=$backup" ($LocalDatabaseUrl -replace '^jdbc:','');if($LASTEXITCODE -ne 0){throw 'Local promotion safety backup failed'}
$uploadHeaders=@{Authorization="Bearer $AdminToken";'Content-Type'='application/octet-stream'};Invoke-RestMethod -Uri "$ServerUrl/api/authority/backups/restore/stage?filename=promotion-local-safety.pgbackup" -Method Post -Headers $uploadHeaders -InFile $backup|Out-Null
Write-Host 'Promotion staged safely. Apply the staged restore on the server, restart it, verify READY, then rerun this command with -Finalize. Local mode has not been changed.'
