param([Parameter(Mandatory=$true)][string]$PostgresHome)
$ErrorActionPreference='Stop';$project=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$parent=(Resolve-Path (Join-Path $project '..')).Path;$root=Join-Path $parent 'runtime-8.5.3-smoke';if(!$root.StartsWith($parent+'\')){throw 'Unsafe smoke path'};if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force};New-Item -ItemType Directory -Path $root|Out-Null
$data=Join-Path $root 'data';$pgLog=Join-Path $root 'postgres.log';$serverOut=Join-Path $root 'server.log';$serverErr=Join-Path $root 'server.err.log';$serverWorkspace=Join-Path $root 'workspace';$server=$null
& (Join-Path $PostgresHome 'bin\initdb.exe') -D $data -U postgres -A trust --no-locale|Out-Null;if($LASTEXITCODE){throw 'initdb failed'};& (Join-Path $PostgresHome 'bin\pg_ctl.exe') -D $data -l $pgLog -o '-p 55992 -h 127.0.0.1' start|Out-Null;if($LASTEXITCODE){throw 'PostgreSQL start failed'}
try{&(Join-Path $PostgresHome 'bin\createdb.exe') -h 127.0.0.1 -p 55992 -U postgres dse_erp;if($LASTEXITCODE){throw 'createdb failed'};$env:DSE_DB_URL='jdbc:postgresql://127.0.0.1:55992/dse_erp';$env:DSE_DB_USERNAME='postgres';$env:DSE_DB_PASSWORD='';$env:DSE_SERVER_PORT='58091';$env:DSE_SERVER_ADDRESS='127.0.0.1';$env:DSE_WORKSPACE_PATH=$serverWorkspace;$env:DSE_POSTGRES_HOME=$PostgresHome;$env:DSE_BUSINESS_TIME_ZONE='Asia/Calcutta';$env:DSE_BUSINESS_DATE_FORMAT='dd/MM/yyyy';$jar=Join-Path $project 'server\target\dse-erp-server.jar';$server=Start-Process -FilePath 'java.exe' -ArgumentList "-jar `"$jar`"" -RedirectStandardOutput $serverOut -RedirectStandardError $serverErr -WindowStyle Hidden -PassThru;$base='http://127.0.0.1:58091';$ready=$false;for($i=0;$i -lt 120;$i++){Start-Sleep -Milliseconds 500;if($server.HasExited){throw "Server exited $($server.ExitCode): $(Get-Content $serverErr -Raw)"};try{$health=Invoke-RestMethod "$base/api/runtime/health";if($health.ready){$ready=$true;break}}catch{}};if(!$ready){throw 'Server did not become READY'}
$bootstrap=@{companyName='Concurrency Test';phone='9999999999';companyEmail='admin@example.test';gstin='24ABCDE1234F1Z5';address='Test';adminName='Admin';adminUsername='admin';adminEmail='admin@example.test';adminPassword='Admin1234'}|ConvertTo-Json;Invoke-RestMethod "$base/api/setup/bootstrap" -Method Post -ContentType application/json -Body $bootstrap|Out-Null
function Login([string]$identity){$body=@{identity=$identity;password='Admin1234'}|ConvertTo-Json;return (Invoke-RestMethod "$base/api/auth/login" -Method Post -ContentType application/json -Body $body).accessToken};$admin=Login 'admin';$adminHeaders=@{Authorization="Bearer $admin"};foreach($u in @('manager1','sales1')){$role=if($u -eq 'manager1'){'MANAGER'}else{'SALES'};$body=@{username=$u;password='Admin1234';fullName=$u;email="$u@example.test";role=$role}|ConvertTo-Json;Invoke-RestMethod "$base/api/auth/register" -Method Post -Headers $adminHeaders -ContentType application/json -Body $body|Out-Null};$manager=Login 'manager1';$sales=Login 'sales1'
& (Join-Path $PSScriptRoot 'test-multi-user-concurrency.ps1') -ServerUrl $base -User1Token $admin -User2Token $manager -User3Token $sales
$bytes=[Text.Encoding]::UTF8.GetBytes('server-authoritative-resource');Invoke-RestMethod "$base/api/authority/resources/BUSINESS_ASSET/company.logoPath?filename=logo.bin" -Method Put -Headers $adminHeaders -ContentType application/octet-stream -Body $bytes|Out-Null;$download=Invoke-WebRequest "$base/api/authority/resources/BUSINESS_ASSET/company.logoPath" -Headers $adminHeaders;if([Text.Encoding]::UTF8.GetString($download.Content) -ne 'server-authoritative-resource'){throw 'Resource round-trip failed'}
$body=@{value='Authoritative Company'}|ConvertTo-Json;Invoke-RestMethod "$base/api/support/settings/company.name" -Method Put -Headers $adminHeaders -ContentType application/json -Body $body|Out-Null;$setting=Invoke-RestMethod "$base/api/support/settings/company.name?def=none" -Headers @{Authorization="Bearer $sales"};if($setting.value -ne 'Authoritative Company'){throw 'Setting round-trip failed'};$backup=Invoke-RestMethod "$base/api/authority/backups" -Method Post -Headers $adminHeaders;if($backup.size -le 0){throw 'Server backup failed'}
Write-Host "RUNTIME_841_OK version=$($health.version) zone=$($health.businessZone) setting=$($setting.value) backup=$($backup.name) bytes=$($backup.size)"
}finally{if($server -and !$server.HasExited){Stop-Process -Id $server.Id -Force};&(Join-Path $PostgresHome 'bin\pg_ctl.exe') -D $data stop -m fast|Out-Null}
