package org.example.controller;
import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.scene.control.cell.CheckBoxTableCell;import org.example.api.admin.AdminApiClient;import org.example.util.IconFactory;import java.util.*;
public class PermissionMatrixController {
 private static String requestedRole; public static void requestRole(String r){requestedRole=r;}
 @FXML private ComboBox<String> cmbRole;@FXML private TableView<Row> table;@FXML private TableColumn<Row,String> colModule,colAction,colDescription;@FXML private TableColumn<Row,Boolean> colAllowed;@FXML private Label lblGranted,lblDenied,lblHint;@FXML private Button btnBack,btnSaveTop,btnGrantAll,btnRevokeAll,btnReset,btnSaveBottom;
 private final ObservableList<Row> rows=FXCollections.observableArrayList(); private final AdminApiClient api=new AdminApiClient();
 @FXML private void initialize(){colModule.setCellValueFactory(v->v.getValue().module);colAction.setCellValueFactory(v->v.getValue().action);colDescription.setCellValueFactory(v->v.getValue().description);colAllowed.setCellValueFactory(v->v.getValue().allowed);colAllowed.setCellFactory(CheckBoxTableCell.forTableColumn(colAllowed));IconFactory.applyTableHeaderIcon(colModule,"master");IconFactory.applyTableHeaderIcon(colAction,"actions");IconFactory.applyTableHeaderIcon(colDescription,"notes");IconFactory.applyTableHeaderIcon(colAllowed,"permission");if(btnBack!=null)btnBack.setGraphic(IconFactory.compactIcon("previous",16));if(btnSaveTop!=null)btnSaveTop.setGraphic(IconFactory.compactIcon("save",16));if(btnSaveBottom!=null)btnSaveBottom.setGraphic(IconFactory.compactIcon("save",16));if(btnGrantAll!=null)btnGrantAll.setGraphic(IconFactory.compactIcon("complete",16));if(btnRevokeAll!=null)btnRevokeAll.setGraphic(IconFactory.compactIcon("cancel",16));if(btnReset!=null)btnReset.setGraphic(IconFactory.compactIcon("reset",16));table.setEditable(true);colAllowed.setEditable(true);table.setItems(rows);loadRoles();cmbRole.valueProperty().addListener((o,a,b)->load(b));if(requestedRole!=null&&cmbRole.getItems().contains(requestedRole))cmbRole.setValue(requestedRole);else if(!cmbRole.getItems().isEmpty())cmbRole.getSelectionModel().selectFirst();requestedRole=null;}
 private void loadRoles(){try{cmbRole.getItems().setAll(api.roles().stream().filter(AdminApiClient.RoleDto::active).map(AdminApiClient.RoleDto::name).toList());}catch(Exception ignored){}}
 private void load(String role){rows.clear();if(role==null)return;try{for(var p:api.permissions(role))rows.add(new Row(p.id(),p.module(),p.action(),p.description(),p.allowed()));}catch(Exception ignored){}update();lblHint.setText("ADMIN".equalsIgnoreCase(role)?"Administrator receives full access by system policy.":"Configure granular access for "+role+".");}
 @FXML private void save(){String role=cmbRole.getValue();if(role==null||role.equalsIgnoreCase("ADMIN"))return;try{api.savePermissions(role,rows.stream().map(x->new AdminApiClient.PermissionSave(x.id,x.allowed.get())).toList());}catch(Exception e){new Alert(Alert.AlertType.ERROR,e.getMessage()).showAndWait();}update();}
 @FXML private void reset(){load(cmbRole.getValue());}@FXML private void grantAll(){rows.forEach(x->x.allowed.set(true));update();}@FXML private void revokeAll(){if(!"ADMIN".equalsIgnoreCase(cmbRole.getValue()))rows.forEach(x->x.allowed.set(false));update();}@FXML private void back(){DashboardController.navigateFromChildPage("Role Management","/fxml/pages/RoleManagement.fxml");}
 private void update(){long g=rows.stream().filter(x->x.allowed.get()).count();lblGranted.setText(String.valueOf(g));lblDenied.setText(String.valueOf(rows.size()-g));}
 public static class Row{final long id;final StringProperty module=new SimpleStringProperty(),action=new SimpleStringProperty(),description=new SimpleStringProperty();final BooleanProperty allowed=new SimpleBooleanProperty();Row(long i,String m,String a,String d,boolean x){id=i;module.set(m);action.set(a);description.set(d);allowed.set(x);}}
}
