package org.example.controller;

import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.scene.layout.*;import org.example.api.recon.PurchaseReconApiClient;import org.example.service.PermissionService;import org.example.navigation.ScreenLifecycle;import org.example.util.*;import java.util.*;
public class ReconSupplierController implements ScreenLifecycle{
 @FXML private StackPane pageIcon,kpiTotalIcon,kpiActiveIcon,kpiImportIcon,kpiReconIcon;@FXML private Label kpiTotal,kpiActive,kpiImported,kpiRecons,lblEditorTitle,lblReference;@FXML private TextField txtSearch,txtName,txtGstin,txtPan,txtContact,txtPhone,txtEmail;@FXML private TextArea txtNotes;@FXML private ComboBox<String> cmbStatus;@FXML private Button btnNew,btnSave,btnRefresh;@FXML private VBox editorPanel;@FXML private TableView<PurchaseReconApiClient.SupplierDto> table;@FXML private TableColumn<PurchaseReconApiClient.SupplierDto,String> colRef,colName,colGstin,colPhone,colSource,colStatus;@FXML private TableColumn<PurchaseReconApiClient.SupplierDto,Number> colCount;@FXML private TableColumn<PurchaseReconApiClient.SupplierDto,Void> colAction;
 private final PurchaseReconApiClient api=new PurchaseReconApiClient();private final ObservableList<PurchaseReconApiClient.SupplierDto> all=FXCollections.observableArrayList();private PurchaseReconApiClient.SupplierDto editing;
 @FXML private void initialize(){pageIcon.getChildren().setAll(IconFactory.icon("supplier",24));kpiTotalIcon.getChildren().setAll(IconFactory.icon("supplier",18));kpiActiveIcon.getChildren().setAll(IconFactory.icon("complete",18));kpiImportIcon.getChildren().setAll(IconFactory.icon("import",18));kpiReconIcon.getChildren().setAll(IconFactory.icon("reconcile",18));if(btnRefresh!=null)btnRefresh.setGraphic(IconFactory.compactIcon("refresh",14));if(btnNew!=null)btnNew.setGraphic(IconFactory.compactIcon("add",14));if(btnSave!=null)btnSave.setGraphic(IconFactory.compactIcon("save",14));cmbStatus.getItems().setAll("ACTIVE","INACTIVE");cmbStatus.setValue("ACTIVE");configureTable();btnNew.setDisable(!PermissionService.allowed("RECON_SUPPLIER.CREATE"));editorPanel.setManaged(false);editorPanel.setVisible(false);org.example.util.OperationalUiSupport.focusSearch(txtSearch);refresh();}
 private void configureTable(){colRef.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().reference())));colName.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().legalName())));colGstin.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().gstin())));colPhone.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().phone())));colCount.setCellValueFactory(v->new SimpleLongProperty(v.getValue().reconCount()));colSource.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().source())));colStatus.setCellValueFactory(v->new SimpleStringProperty(s(v.getValue().status())));colAction.setCellFactory(c->new TableCell<>(){@Override protected void updateItem(Void x,boolean empty){super.updateItem(x,empty);if(empty||getIndex()<0||getIndex()>=getTableView().getItems().size()){setGraphic(null);return;}Button b=new Button("Edit");b.setGraphic(IconFactory.compactIcon("edit",14));b.getStyleClass().addAll("approved-button","approved-secondary-button");var row=getTableView().getItems().get(getIndex());b.setDisable(!PermissionService.allowed("RECON_SUPPLIER.EDIT"));b.setOnAction(e->edit(row));setGraphic(b);}});IconFactory.applyTableHeaderIcon(colRef,"reference");IconFactory.applyTableHeaderIcon(colName,"supplier");IconFactory.applyTableHeaderIcon(colGstin,"tax");IconFactory.applyTableHeaderIcon(colPhone,"phone");IconFactory.applyTableHeaderIcon(colCount,"purchase");IconFactory.applyTableHeaderIcon(colSource,"source");IconFactory.applyTableHeaderIcon(colStatus,"status");IconFactory.applyTableHeaderIcon(colAction,"actions");table.setRowFactory(tv->{TableRow<PurchaseReconApiClient.SupplierDto> r=new TableRow<>();r.setOnMouseClicked(e->{if(e.getClickCount()==2&&!r.isEmpty())edit(r.getItem());});return r;});}
 @Override public void onScreenShown(boolean reusedFromCache){org.example.util.OperationalUiSupport.focusSearch(txtSearch);if(reusedFromCache)refresh();}
 @FXML private void refresh(){org.example.util.OperationalUiSupport.showLoading(table,"Loading recon suppliers…");UiTaskExecutor.submitLatest("recon-supplier-load",api::suppliers,list->{all.setAll(list==null?List.of():list);applySearch();updateKpis();},failure->{org.example.util.OperationalUiSupport.showError(table,"Recon Supplier register could not load",failure);error(failure);});}
 @FXML private void applySearch(){String q=s(txtSearch.getText()).trim().toLowerCase(Locale.ROOT);table.getItems().setAll(all.stream().filter(x->q.isBlank()||String.join(" ",s(x.reference()),s(x.legalName()),s(x.gstin()),s(x.phone()),s(x.email())).toLowerCase(Locale.ROOT).contains(q)).toList());if(table.getItems().isEmpty())org.example.util.OperationalUiSupport.showEmpty(table,"No recon suppliers found","Create a Recon Supplier or update the search.");}
 private void updateKpis(){kpiTotal.setText(String.valueOf(all.size()));kpiActive.setText(String.valueOf(all.stream().filter(x->"ACTIVE".equalsIgnoreCase(x.status())).count()));kpiImported.setText(String.valueOf(all.stream().filter(x->"IMPORT".equalsIgnoreCase(x.source())).count()));kpiRecons.setText(String.valueOf(all.stream().mapToLong(PurchaseReconApiClient.SupplierDto::reconCount).sum()));}
 @FXML private void newSupplier(){editing=null;txtName.clear();txtGstin.clear();txtPan.clear();txtContact.clear();txtPhone.clear();txtEmail.clear();txtNotes.clear();cmbStatus.setValue("ACTIVE");lblEditorTitle.setText("New Recon Supplier");lblReference.setText("Reference generated on save");btnSave.setDisable(!PermissionService.allowed("RECON_SUPPLIER.CREATE"));showEditor();}
 private void edit(PurchaseReconApiClient.SupplierDto x){if(x==null)return;editing=x;txtName.setText(s(x.legalName()));txtGstin.setText(s(x.gstin()));txtPan.setText(s(x.pan()));txtContact.setText(s(x.contactPerson()));txtPhone.setText(s(x.phone()));txtEmail.setText(s(x.email()));txtNotes.setText(s(x.notes()));cmbStatus.setValue(s(x.status()).isBlank()?"ACTIVE":x.status());lblEditorTitle.setText("Edit Recon Supplier");lblReference.setText(s(x.reference()));btnSave.setDisable(!PermissionService.allowed("RECON_SUPPLIER.EDIT"));showEditor();}
 private void showEditor(){editorPanel.setManaged(true);editorPanel.setVisible(true);txtName.requestFocus();}
 @FXML private void cancelEdit(){editorPanel.setManaged(false);editorPanel.setVisible(false);editing=null;}
 @FXML private void saveSupplier(){if(txtName.getText()==null||txtName.getText().isBlank()){ModernDialog.warning(table,"Recon Supplier","Name required","Enter the Trade / Legal Name.");return;}var req=new PurchaseReconApiClient.SupplierSaveRequest(editing==null?null:editing.id(),txtName.getText().trim(),s(txtGstin.getText()).trim(),s(txtPan.getText()).trim(),s(txtContact.getText()).trim(),s(txtPhone.getText()).trim(),s(txtEmail.getText()).trim(),s(txtNotes.getText()).trim(),cmbStatus.getValue(),editing==null?0L:editing.rowVersion());UiTaskExecutor.submitAction("recon-supplier-save",()->api.saveSupplier(req),saved->{ToastManager.success(table,"Recon Supplier saved",saved.reference()+" • "+saved.legalName());cancelEdit();refresh();},this::error);}
 private void error(Throwable e){String m=e==null?"Operation failed":e.getMessage();ModernDialog.error(table,"Recon Supplier","Operation failed",m==null?"Operation failed":m);}private static String s(String x){return x==null?"":x;}
}
