package org.example.controller;
import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import org.example.api.admin.AdminApiClient;import org.example.util.OwnedAlert;import org.example.util.OwnedTextInputDialog;
public class RoleManagementController {
 @FXML private TableView<RoleRow> roleTable; @FXML private TableColumn<RoleRow,String> colName,colDescription,colStatus; @FXML private TableColumn<RoleRow,Number> colUsers; @FXML private Label lblRoles,lblAssigned,lblCustom;
 private final ObservableList<RoleRow> rows=FXCollections.observableArrayList(); private final AdminApiClient api=new AdminApiClient();
 @FXML private void initialize(){colName.setCellValueFactory(v->v.getValue().name);colDescription.setCellValueFactory(v->v.getValue().description);colUsers.setCellValueFactory(v->v.getValue().users);colStatus.setCellValueFactory(v->v.getValue().status);roleTable.setItems(rows);refresh();}
 @FXML private void refresh(){rows.clear();try{for(var r:api.roles())rows.add(new RoleRow(r.id(),r.name(),r.description(),(int)r.userCount(),r.active()));}catch(Exception e){alert("Roles could not be loaded",e.getMessage());}lblRoles.setText(String.valueOf(rows.size()));lblAssigned.setText(String.valueOf(rows.stream().mapToInt(x->x.users.get()).sum()));lblCustom.setText(String.valueOf(rows.size()));}
 @FXML private void addRole(){TextInputDialog d=new OwnedTextInputDialog();d.setTitle("Add Role");d.setHeaderText("Create a new system role");d.setContentText("Role name:");d.showAndWait().map(String::trim).filter(x->!x.isBlank()).ifPresent(n->{try{api.saveRole(new AdminApiClient.RoleSaveRequest(null,n.toUpperCase(),"Custom ERP role",true));refresh();}catch(Exception e){alert("Role could not be created",e.getMessage());}});}
 @FXML private void editRole(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();if(x==null)return;TextInputDialog d=new OwnedTextInputDialog(x.description.get());d.setTitle("Edit Role");d.setHeaderText(x.name.get());d.setContentText("Description:");d.showAndWait().ifPresent(v->{try{api.saveRole(new AdminApiClient.RoleSaveRequest((int)x.id,x.name.get(),v.trim(),"Active".equals(x.status.get())));refresh();}catch(Exception e){alert("Role could not be updated",e.getMessage());}});}
 @FXML private void deleteRole(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();if(x==null||x.name.get().equalsIgnoreCase("ADMIN"))return;Alert a=new OwnedAlert(Alert.AlertType.CONFIRMATION,"Delete role "+x.name.get()+"?",ButtonType.YES,ButtonType.NO);if(a.showAndWait().orElse(ButtonType.NO)!=ButtonType.YES)return;try{api.deleteRole((int)x.id);refresh();}catch(Exception e){alert("Role could not be deleted","Remove assigned users first. "+e.getMessage());}}
 @FXML private void openPermissions(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();PermissionMatrixController.requestRole(x==null?null:x.name.get());DashboardController.navigateFromChildPage("Permission Matrix","/fxml/pages/PermissionMatrix.fxml");}
 @FXML private void back(){DashboardController.navigateFromChildPage("User Access & Permissions","/fxml/pages/UserAccess.fxml");}
 private void alert(String h,String c){Alert a=new OwnedAlert(Alert.AlertType.ERROR);a.setHeaderText(h);a.setContentText(c);a.showAndWait();}
 public static class RoleRow{final long id;final StringProperty name=new SimpleStringProperty(),description=new SimpleStringProperty(),status=new SimpleStringProperty();final IntegerProperty users=new SimpleIntegerProperty();RoleRow(long i,String n,String d,int u,boolean a){id=i;name.set(n);description.set(d==null?"":d);users.set(u);status.set(a?"Active":"Inactive");}}
}
