package org.example.api.workflow;
import com.fasterxml.jackson.core.type.TypeReference; import org.example.api.ApiRuntime; import org.example.config.ConfigManager;
import java.math.BigDecimal; import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*;
public final class WorkflowApiClient {
 private final HttpClient http=ApiRuntime.HTTP; private final com.fasterxml.jackson.databind.ObjectMapper json=ApiRuntime.JSON;
 public WorkflowApiClient(){}
 private static String base(){String b=ConfigManager.getDataApiBaseUrl();while(b.endsWith("/"))b=b.substring(0,b.length()-1);return b;}
 public record Line(Integer id,Integer lineNo,String itemCode,String description,BigDecimal quantity,BigDecimal rate,BigDecimal amount){}
 public record Document(Integer id,String documentType,String documentNo,LocalDate documentDate,String projectNo,String parentNo,String partyName,Integer partyId,String customerPoNo,LocalDate expectedDate,String status,BigDecimal totalAmount,String notes,long rowVersion,List<Line> lines){}
 public record StockAvailability(String itemCode,String description,BigDecimal onHand,BigDecimal reserved,BigDecimal currentOrderReserved,BigDecimal freeToPromise){}
 public record ProjectProfitability(String projectNo,BigDecimal salesOrdered,BigDecimal purchaseCommitted,BigDecimal salesInvoiced,BigDecimal purchaseInvoiced,BigDecimal grossProfit,BigDecimal grossMarginPercent){}
 public StockAvailability stockAvailability(String itemCode,Integer documentId){String path="/api/workflow/stock-availability?itemCode="+enc(itemCode)+(documentId==null?"":"&documentId="+documentId);return request("GET",path,null,StockAvailability.class,null);}
 public ProjectProfitability profitability(String projectNo){return request("GET","/api/workflow/project-profitability?projectNo="+enc(projectNo),null,ProjectProfitability.class,null);}
 public List<Document> list(String type){return request("GET","/api/workflow?type="+enc(type),null,null,new TypeReference<List<Document>>(){});} public Document get(int id){return request("GET","/api/workflow/"+id,null,Document.class,null);} public Document save(Document d){return request(d.id()==null?"POST":"PUT","/api/workflow",d,Document.class,null);} public void delete(int id,long v){request("DELETE","/api/workflow/"+id+"?rowVersion="+v,null,Map.class,null);} public String next(String type){return request("GET","/api/workflow/next-number?type="+enc(type),null,NextNumber.class,null).value();} private record NextNumber(String value){}
 private static String enc(String s){return URLEncoder.encode(s==null?"":s,StandardCharsets.UTF_8);}
 private <T>T request(String method,String path,Object body,Class<T> cls,TypeReference<T> type){String endpoint=base();try{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(endpoint+path)).timeout(java.time.Duration.ofSeconds(25)).header("Accept","application/json");org.example.api.ApiSession.authorize(b);if(body!=null){b.header("Content-Type","application/json").method(method,HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));}else b.method(method,HttpRequest.BodyPublishers.noBody());var r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()<200||r.statusCode()>=300){ApiRuntime.logHttpFailure("Workflow operation",r.statusCode(),r.body());throw new IllegalStateException(ApiRuntime.userMessage("workflow operation",r.statusCode(),r.body()));}return type!=null?json.readValue(r.body(),type):json.readValue(r.body(),cls);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalStateException("Workflow request interrupted",e);}catch(Exception e){if(e instanceof IllegalStateException x)throw x;throw new IllegalStateException(ApiRuntime.transportMessage("Workflow request",endpoint,e),e);}}
}
