package org.example.server.support;
import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/support") public class SupportController {private final SupportService s;public SupportController(SupportService s){this.s=s;}
 @GetMapping("/saved-views") public List<SupportDtos.SavedView> views(@RequestParam String screen,@RequestParam(required=false) Integer userId){return s.savedViews(screen,userId);}@PostMapping("/saved-views") public SupportDtos.Ok view(@RequestBody SupportDtos.SavedViewSave d){s.saveView(d);return ok("Saved");}
 @GetMapping("/payments") public List<SupportDtos.PaymentRow> payments(@RequestParam String type,@RequestParam int id){return s.payments(type,id);}@PostMapping("/payments") public SupportDtos.Ok payment(@RequestBody SupportDtos.PaymentRequest d){s.recordPayment(d);return ok("Recorded");}@PutMapping("/payments/{paymentId}") public SupportDtos.Ok payment(@PathVariable int paymentId,@RequestBody SupportDtos.PaymentUpdateRequest d){s.updatePayment(paymentId,d);return ok("Updated");}
 @GetMapping("/communications") public List<SupportDtos.CommunicationRow> communications(){return s.communications();}@PostMapping("/communications") public SupportDtos.Ok communication(@RequestBody SupportDtos.CommunicationRequest d){s.communication(d);return ok("Saved");}
 @PostMapping("/documents/{type}/{id}/whatsapp") public SupportDtos.Ok whatsapp(@PathVariable String type,@PathVariable int id){s.markWhatsappSent(type,id);return ok("Updated");}@PutMapping("/documents/{type}/{id}/attachment") public SupportDtos.Ok attachment(@PathVariable String type,@PathVariable int id,@RequestBody SupportDtos.Text d){s.setAttachment(type,id,d.value());return ok("Updated");}@PutMapping("/documents/{type}/{id}/notes") public SupportDtos.Ok notes(@PathVariable String type,@PathVariable int id,@RequestBody SupportDtos.Text d){s.setNotes(type,id,d.value());return ok("Updated");}
 @PostMapping("/activity") public SupportDtos.Ok activity(@RequestParam String type,@RequestParam int id,@RequestParam String action,@RequestParam(defaultValue="") String detail,@RequestParam(defaultValue="System") String user){s.activity(type,id,action,detail,user);return ok("Saved");}@GetMapping("/returns/{no}/party-email") public SupportDtos.Text returnEmail(@PathVariable String no){return new SupportDtos.Text(s.returnPartyEmail(no));}@PostMapping("/sales/{id}/duplicate") public SupportDtos.Text duplicateSale(@PathVariable int id,@RequestParam(defaultValue="System") String user){return new SupportDtos.Text(s.duplicateSale(id,user));}@PostMapping("/purchases/{id}/cancel") public SupportDtos.Ok cancelPurchase(@PathVariable int id){s.cancelPurchase(id);return ok("Deleted");}
 @GetMapping("/search") public List<SupportDtos.SearchRow> search(@RequestParam String q){return s.search(q);}@GetMapping("/business-report") public SupportDtos.ReportSummary report(@RequestParam String from,@RequestParam String to){return s.businessReport(from,to);}
 @GetMapping("/settings/{key}") public SupportDtos.Text setting(@PathVariable String key,@RequestParam(defaultValue="") String def){return new SupportDtos.Text(s.setting(key,def));}@PutMapping("/settings/{key}") public SupportDtos.Ok setting(@PathVariable String key,@RequestBody SupportDtos.Text d){s.setSetting(key,d.value());return ok("Saved");}
 @PostMapping("/backup/ensure") public SupportDtos.Ok ensure(){s.ensureBackupTables();return ok("Ready");}@PostMapping("/backup/application-metadata") public SupportDtos.Ok appMeta(@RequestParam String appId,@RequestParam int schemaVersion,@RequestParam String appVersion){s.ensureApplicationMetadata(appId,schemaVersion,appVersion);return ok("Ready");}@GetMapping("/backup/meta") public SupportDtos.BackupMeta meta(@RequestParam String file){return s.backupMeta(file);}@PutMapping("/backup/meta") public SupportDtos.Ok meta(@RequestBody SupportDtos.BackupMeta d){s.saveBackupMeta(d);return ok("Saved");}@PostMapping("/backup/legacy-constraints") public SupportDtos.Ok constraints(@RequestParam boolean add){s.legacyConstraints(add);return ok("Updated");}
 private SupportDtos.Ok ok(String m){return new SupportDtos.Ok(true,m);}}
