package org.example.server.support;
import org.springframework.web.bind.annotation.*;import org.springframework.http.*;import java.util.*;import java.nio.charset.StandardCharsets;
@RestController @RequestMapping("/api/support") public class SupportController {private final SupportService s;public SupportController(SupportService s){this.s=s;}
 @GetMapping("/saved-views") public List<SupportDtos.SavedView> views(@RequestParam String screen,@RequestParam(required=false) Integer userId){return s.savedViews(screen,userId);}@PostMapping("/saved-views") public SupportDtos.Ok view(@RequestBody SupportDtos.SavedViewSave d){s.saveView(d);return ok("Saved");}
 @GetMapping("/payments") public List<SupportDtos.PaymentRow> payments(@RequestParam String type,@RequestParam int id){return s.payments(type,id);}@PostMapping("/payments") public SupportDtos.Ok payment(@RequestBody SupportDtos.PaymentRequest d){s.recordPayment(d);return ok("Recorded");}@PostMapping("/payments/with-id") public SupportDtos.PaymentCreated paymentWithId(@RequestBody SupportDtos.PaymentRequest d){return new SupportDtos.PaymentCreated(s.recordPaymentWithId(d));}@PutMapping("/payments/{paymentId}") public SupportDtos.Ok payment(@PathVariable int paymentId,@RequestBody SupportDtos.PaymentUpdateRequest d){s.updatePayment(paymentId,d);return ok("Updated");}@PutMapping("/payments/{paymentId}/attachment") public SupportDtos.Ok paymentAttachment(@PathVariable int paymentId,@RequestBody SupportDtos.Text d){s.updatePaymentAttachment(paymentId,d.value());return ok("Updated");}
 @PutMapping(value="/documents/{type}/{id}/attachment-file",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) public SupportDtos.Text uploadDocumentAttachment(@PathVariable String type,@PathVariable int id,@RequestParam String filename,@RequestBody byte[] data){return new SupportDtos.Text(s.storeDocumentAttachment(type,id,filename,data));}
 @GetMapping(value="/documents/{type}/{id}/attachment-file",produces=MediaType.APPLICATION_OCTET_STREAM_VALUE) public ResponseEntity<byte[]> documentAttachmentFile(@PathVariable String type,@PathVariable int id){return file(s.documentAttachmentFile(type,id));}
 @DeleteMapping("/documents/{type}/{id}/attachment-file") public SupportDtos.Ok deleteDocumentAttachment(@PathVariable String type,@PathVariable int id){s.removeDocumentAttachment(type,id);return ok("Removed");}
 @GetMapping("/documents/{type}/{id}/attachments") public java.util.List<SupportDtos.AttachmentMeta> documentAttachments(@PathVariable String type,@PathVariable int id){return s.documentAttachments(type,id);}
 @PostMapping(value="/documents/{type}/{id}/attachments",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) public SupportDtos.AttachmentMeta addDocumentAttachment(@PathVariable String type,@PathVariable int id,@RequestParam String filename,@RequestBody byte[] data){return s.addDocumentAttachment(type,id,filename,data);}
 @GetMapping(value="/documents/{type}/{id}/attachments/{attachmentId}",produces=MediaType.APPLICATION_OCTET_STREAM_VALUE) public ResponseEntity<byte[]> documentAttachmentFileById(@PathVariable String type,@PathVariable int id,@PathVariable long attachmentId){return file(s.documentAttachmentFile(type,id,attachmentId));}
 @DeleteMapping("/documents/{type}/{id}/attachments/{attachmentId}") public SupportDtos.Ok deleteDocumentAttachmentById(@PathVariable String type,@PathVariable int id,@PathVariable long attachmentId){s.removeDocumentAttachment(type,id,attachmentId);return ok("Removed");}
 @PutMapping(value="/returns/{no}/attachment-file",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) public SupportDtos.Text uploadReturnAttachment(@PathVariable String no,@RequestParam String filename,@RequestBody byte[] data){return new SupportDtos.Text(s.storeReturnAttachment(no,filename,data));}
 @GetMapping(value="/returns/{no}/attachment-file",produces=MediaType.APPLICATION_OCTET_STREAM_VALUE) public ResponseEntity<byte[]> returnAttachmentFile(@PathVariable String no){return file(s.returnAttachmentFile(no));}
 @DeleteMapping("/returns/{no}/attachment-file") public SupportDtos.Ok deleteReturnAttachment(@PathVariable String no){s.removeReturnAttachment(no);return ok("Removed");}
 @PutMapping(value="/payments/{paymentId}/attachment-file",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) public SupportDtos.Text uploadPaymentAttachment(@PathVariable int paymentId,@RequestParam String filename,@RequestBody byte[] data){return new SupportDtos.Text(s.storePaymentAttachment(paymentId,filename,data));}
 @GetMapping(value="/payments/{paymentId}/attachment-file",produces=MediaType.APPLICATION_OCTET_STREAM_VALUE) public ResponseEntity<byte[]> paymentAttachmentFile(@PathVariable int paymentId){return file(s.paymentAttachmentFile(paymentId));}
 @DeleteMapping("/payments/{paymentId}/attachment-file") public SupportDtos.Ok deletePaymentAttachment(@PathVariable int paymentId){s.removePaymentAttachment(paymentId);return ok("Removed");}
 @PutMapping(value="/return-refunds/{refundId}/attachment-file",consumes=MediaType.APPLICATION_OCTET_STREAM_VALUE) public SupportDtos.Text uploadReturnRefundAttachment(@PathVariable int refundId,@RequestParam String filename,@RequestBody byte[] data){return new SupportDtos.Text(s.storeReturnRefundAttachment(refundId,filename,data));}
 @GetMapping(value="/return-refunds/{refundId}/attachment-file",produces=MediaType.APPLICATION_OCTET_STREAM_VALUE) public ResponseEntity<byte[]> returnRefundAttachmentFile(@PathVariable int refundId){return file(s.returnRefundAttachmentFile(refundId));}
 @DeleteMapping("/return-refunds/{refundId}/attachment-file") public SupportDtos.Ok deleteReturnRefundAttachment(@PathVariable int refundId){s.removeReturnRefundAttachment(refundId);return ok("Removed");}
 @GetMapping("/communications") public List<SupportDtos.CommunicationRow> communications(){return s.communications();}@PostMapping("/communications") public SupportDtos.Ok communication(@RequestBody SupportDtos.CommunicationRequest d){s.communication(d);return ok("Saved");}
 @PostMapping("/documents/{type}/{id}/whatsapp") public SupportDtos.Ok whatsapp(@PathVariable String type,@PathVariable int id){s.markWhatsappSent(type,id);return ok("Updated");}@PutMapping("/documents/{type}/{id}/notes") public SupportDtos.Ok notes(@PathVariable String type,@PathVariable int id,@RequestBody SupportDtos.Text d){s.setNotes(type,id,d.value());return ok("Updated");}
 @PostMapping("/activity") public SupportDtos.Ok activity(@RequestParam String type,@RequestParam int id,@RequestParam String action,@RequestParam(defaultValue="") String detail,@RequestParam(defaultValue="System") String user){s.activity(type,id,action,detail,user);return ok("Saved");}@GetMapping("/returns/{no}/party-email") public SupportDtos.Text returnEmail(@PathVariable String no){return new SupportDtos.Text(s.returnPartyEmail(no));}@PostMapping("/sales/{id}/duplicate") public SupportDtos.Text duplicateSale(@PathVariable int id,@RequestParam(defaultValue="System") String user){return new SupportDtos.Text(s.duplicateSale(id,user));}@PostMapping("/purchases/{id}/cancel") public SupportDtos.Ok cancelPurchase(@PathVariable int id){s.cancelPurchase(id);return ok("Cancelled");}
 @GetMapping("/search") public List<SupportDtos.SearchRow> search(@RequestParam String q){return s.search(q);}@GetMapping("/resolve-record") public SupportDtos.ResolvedRecord resolveRecord(@RequestParam String moduleKey,@RequestParam String reference){return s.resolveRecord(moduleKey,reference);}@GetMapping("/business-report") public SupportDtos.ReportSummary report(@RequestParam String from,@RequestParam String to){return s.businessReport(from,to);}
 @GetMapping("/settings/{key}") public SupportDtos.Text setting(@PathVariable String key,@RequestParam(defaultValue="") String def){return new SupportDtos.Text(s.setting(key,def));}@PutMapping("/settings/{key}") public SupportDtos.Ok setting(@PathVariable String key,@RequestBody SupportDtos.Text d){s.setSetting(key,d.value());return ok("Saved");}
 @PostMapping("/backup/ensure") public SupportDtos.Ok ensure(){s.ensureBackupTables();return ok("Ready");}@PostMapping("/backup/application-metadata") public SupportDtos.Ok appMeta(@RequestParam String appId,@RequestParam int schemaVersion,@RequestParam String appVersion){s.ensureApplicationMetadata(appId,schemaVersion,appVersion);return ok("Ready");}@GetMapping("/backup/meta") public SupportDtos.BackupMeta meta(@RequestParam String file){return s.backupMeta(file);}@PutMapping("/backup/meta") public SupportDtos.Ok meta(@RequestBody SupportDtos.BackupMeta d){s.saveBackupMeta(d);return ok("Saved");}@PostMapping("/backup/legacy-constraints") public SupportDtos.Ok constraints(@RequestParam boolean add){s.legacyConstraints(add);return ok("Updated");}
 private ResponseEntity<byte[]> file(SupportDtos.AttachmentFile f){String name=f.fileName()==null?"attachment":f.fileName().replace("\"","_");return ResponseEntity.ok().contentType(MediaType.APPLICATION_OCTET_STREAM).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename*=UTF-8''"+java.net.URLEncoder.encode(name,StandardCharsets.UTF_8).replace("+","%20")).header("X-Attachment-Name",java.net.URLEncoder.encode(name,StandardCharsets.UTF_8)).body(f.data());}
 private SupportDtos.Ok ok(String m){return new SupportDtos.Ok(true,m);}}
