package org.example.server.workflow;
import org.example.server.persistence.entity.*; import org.example.server.persistence.repository.*; import org.example.server.persistence.JpaNativeRepository; import org.example.server.security.CurrentUser; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class WorkflowService {
 private static final Set<String> TYPES=Set.of("PROJECT","SALES_ORDER","PURCHASE_ORDER","GRN","DISPATCH");
 private final WorkflowDocumentRepository docs; private final WorkflowDocumentLineRepository lines; private final JpaNativeRepository jdbc; private final ItemRepository items;
 public WorkflowService(WorkflowDocumentRepository d,WorkflowDocumentLineRepository l,JpaNativeRepository jdbc,ItemRepository items){docs=d;lines=l;this.jdbc=jdbc;this.items=items;}
 @Transactional(readOnly=true) public List<WorkflowDtos.Document> list(String type){CurrentUser.requirePermission("PROJECT_EXECUTION.VIEW","View Project Execution");type=type(type);return docs.findByDocumentTypeOrderByDocumentDateDescIdDesc(type).stream().map(this::dto).toList();}
 @Transactional(readOnly=true) public WorkflowDtos.Document get(int id){CurrentUser.requirePermission("PROJECT_EXECUTION.VIEW","View Project Execution");return dto(docs.findById(id).orElseThrow(()->new IllegalArgumentException("Workflow record not found")));}
 @Transactional public WorkflowDtos.Document save(WorkflowDtos.Document d){boolean create=d==null||d.id()==null;CurrentUser.requirePermission(create?"PROJECT_EXECUTION.CREATE":"PROJECT_EXECUTION.EDIT",create?"Create Project Execution record":"Edit Project Execution record");validate(d,create); WorkflowDocumentEntity e=create?new WorkflowDocumentEntity():docs.findByIdForUpdate(d.id()).orElseThrow(()->new IllegalArgumentException("Workflow record not found")); if(!create&&d.rowVersion()!=e.getRowVersion())throw new org.example.server.web.ConcurrentEditException("Workflow record "+e.getDocumentNo()); String assignedNo=create?allocateNumber(type(d.documentType())):e.getDocumentNo();
  Map<String,BigDecimal> oldReservation=!create&&"SALES_ORDER".equals(e.getDocumentType())&&reserves(e.getStatus())?reservationQuantities(lines.findByDocumentIdOrderByLineNo(e.getId()).stream().map(x->new WorkflowDtos.Line(x.getId(),x.getLineNo(),x.getItemCode(),x.getDescription(),x.getQuantity(),x.getRate(),x.getAmount())).toList()):Map.of();
  copy(d,e,assignedNo); Map<String,BigDecimal> newReservation="SALES_ORDER".equals(e.getDocumentType())&&reserves(e.getStatus())?reservationQuantities(safe(d.lines())):Map.of(); adjustReservations(oldReservation,newReservation);
  if(e.getId()==null){e.setCreatedBy(CurrentUser.require().username());e.setCreatedAt(LocalDateTime.now());} e.setUpdatedAt(LocalDateTime.now()); e=docs.saveAndFlush(e); lines.deleteByDocumentId(e.getId()); int n=1; BigDecimal total=BigDecimal.ZERO; for(var l:safe(d.lines())){var x=new WorkflowDocumentLineEntity();x.setDocumentId(e.getId());x.setLineNo(n++);x.setItemCode(trim(l.itemCode()));x.setDescription(req(l.description(),"Line description"));x.setQuantity(nonneg(l.quantity(),"Quantity"));x.setRate(nonneg(l.rate(),"Rate"));x.setAmount(x.getQuantity().multiply(x.getRate()).setScale(2,RoundingMode.HALF_UP));total=total.add(x.getAmount());lines.save(x);} e.setTotalAmount(total.setScale(2,RoundingMode.HALF_UP)); e=docs.saveAndFlush(e); return dto(e);}
 @Transactional public void delete(int id,long version){CurrentUser.requirePermission("PROJECT_EXECUTION.DELETE","Delete Project Execution record");var e=docs.findByIdForUpdate(id).orElseThrow(()->new IllegalArgumentException("Workflow record not found"));if(version!=e.getRowVersion())throw new org.example.server.web.ConcurrentEditException("Workflow record "+e.getDocumentNo());if("SALES_ORDER".equals(e.getDocumentType())&&reserves(e.getStatus()))adjustReservations(reservationQuantities(lines.findByDocumentIdOrderByLineNo(e.getId()).stream().map(x->new WorkflowDtos.Line(x.getId(),x.getLineNo(),x.getItemCode(),x.getDescription(),x.getQuantity(),x.getRate(),x.getAmount())).toList()),Map.of());docs.delete(e);}
 @Transactional(readOnly=true) public String next(String type){CurrentUser.requirePermission("PROJECT_EXECUTION.CREATE","Create Project Execution record");type(type);return "Auto-generated on Save";}
 private String allocateNumber(String type){
  type=type(type);
  String lookupCode=switch(type){case"PROJECT"->"REF_PROJECT";case"SALES_ORDER"->"REF_SALES_ORDER";case"PURCHASE_ORDER"->"REF_PURCHASE_ORDER";case"GRN"->"REF_GRN";default->"REF_DISPATCH";};
  String fallback=switch(type){case"PROJECT"->"PRJ-YYYY-XXXXX";case"SALES_ORDER"->"SO-YYYY-XXXXX";case"PURCHASE_ORDER"->"PO-YYYY-XXXXX";case"GRN"->"GRN-YYYY-XXXXX";default->"DC-YYYY-XXXXX";};
  List<String> configured=jdbc.query("SELECT lm.lookup_value FROM lookup_master lm JOIN master_category mc ON UPPER(TRIM(mc.category_name))=UPPER(TRIM(lm.lookup_type)) WHERE UPPER(TRIM(mc.category_code))='REFERENCE_FORMAT' AND UPPER(TRIM(lm.lookup_code))=? AND COALESCE(lm.is_active,1)<>0 ORDER BY lm.id LIMIT 1",(r,i)->r.getString(1),lookupCode);
  String pattern=configured.isEmpty()||trim(configured.getFirst()).isBlank()?fallback:trim(configured.getFirst());
  int year=Year.now().getValue(); pattern=pattern.replace("YYYY",Integer.toString(year)).replace("YY",String.format(Locale.ROOT,"%02d",year%100));
  java.util.regex.Matcher m=java.util.regex.Pattern.compile("X+").matcher(pattern); int pad=5; String scope=pattern;
  if(m.find()){pad=m.group().length();scope=pattern.substring(0,m.start())+"#"+pattern.substring(m.end());}
  String key="WORKFLOW|"+lookupCode+"|"+scope;
  Long seq=jdbc.queryForObject("INSERT INTO reference_counter(counter_key,next_value,updated_at) VALUES(?,1,CURRENT_TIMESTAMP) ON CONFLICT(counter_key) DO UPDATE SET next_value=reference_counter.next_value+1,updated_at=CURRENT_TIMESTAMP RETURNING next_value",Long.class,key);
  long n=seq==null?1L:seq; m=java.util.regex.Pattern.compile("X+").matcher(pattern);
  return m.find()?pattern.substring(0,m.start())+String.format(Locale.ROOT,"%0"+Math.max(1,pad)+"d",n)+pattern.substring(m.end()):pattern+"-"+n;
 }
 @Transactional(readOnly=true) public WorkflowDtos.StockAvailability stockAvailability(String itemCode,Integer documentId){CurrentUser.requirePermission("PROJECT_EXECUTION.VIEW","View Sales Order stock availability");String code=req(itemCode,"Item code");ItemEntity item=items.findByItemCode(code).orElseThrow(()->new IllegalArgumentException("Item not found: "+code));BigDecimal onHand=BigDecimal.valueOf(item.getOpeningStock()==null?0:item.getOpeningStock());BigDecimal reserved=BigDecimal.valueOf(item.getReservedStock()==null?0:item.getReservedStock());BigDecimal own=BigDecimal.ZERO;if(documentId!=null&&documentId>0){WorkflowDocumentEntity doc=docs.findById(documentId).orElse(null);if(doc!=null&&"SALES_ORDER".equals(doc.getDocumentType())&&reserves(doc.getStatus()))own=lines.findByDocumentIdOrderByLineNo(documentId).stream().filter(l->code.equalsIgnoreCase(trim(l.getItemCode()))).map(l->l.getQuantity()==null?BigDecimal.ZERO:l.getQuantity()).reduce(BigDecimal.ZERO,BigDecimal::add);}BigDecimal free=onHand.subtract(reserved).add(own).max(BigDecimal.ZERO);return new WorkflowDtos.StockAvailability(code,trim(item.getDescription()),onHand,reserved,own,free);}
 private static boolean reserves(String status){String s=trim(status).toUpperCase(Locale.ROOT);return !"COMPLETED".equals(s)&&!"CANCELLED".equals(s);}
 private static Map<String,BigDecimal> reservationQuantities(List<WorkflowDtos.Line> source){Map<String,BigDecimal> out=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);for(var line:safe(source)){String code=trim(line.itemCode());if(code.isBlank())continue;out.merge(code,nonneg(line.quantity(),"Quantity"),BigDecimal::add);}return out;}
 private void adjustReservations(Map<String,BigDecimal> oldValues,Map<String,BigDecimal> newValues){Set<String> codes=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);codes.addAll(oldValues.keySet());codes.addAll(newValues.keySet());for(String code:codes){ItemEntity item=items.findByItemCodeForUpdate(code).orElseThrow(()->new IllegalArgumentException("Item not found: "+code));BigDecimal current=BigDecimal.valueOf(item.getReservedStock()==null?0:item.getReservedStock());BigDecimal next=current.subtract(oldValues.getOrDefault(code,BigDecimal.ZERO)).add(newValues.getOrDefault(code,BigDecimal.ZERO));if(next.signum()<0&&next.abs().compareTo(new BigDecimal("0.0001"))<=0)next=BigDecimal.ZERO;if(next.signum()<0)throw new IllegalStateException("Reserved stock became negative for "+code);item.setReservedStock(next.doubleValue());items.save(item);}}
 @Transactional(readOnly=true) public WorkflowDtos.ProjectProfitability profitability(String projectNo){CurrentUser.requirePermission("PROJECT_EXECUTION.VIEW","View Project Profitability");String project=req(projectNo,"Project number");requireDocument("PROJECT",project,"Project");BigDecimal salesOrdered=sumWorkflow("SALES_ORDER",project);BigDecimal purchaseCommitted=sumWorkflow("PURCHASE_ORDER",project);BigDecimal salesInvoiced=money(jdbc.queryForObject("SELECT COALESCE(SUM(total_amount),0) FROM sales_header WHERE project_no=? AND UPPER(COALESCE(document_status,'')) NOT IN ('DELETED','CANCELLED')",BigDecimal.class,project));BigDecimal purchaseInvoiced=money(jdbc.queryForObject("SELECT COALESCE(SUM(total_amount),0) FROM purchase_header WHERE project_no=? AND UPPER(COALESCE(document_status,'')) NOT IN ('DELETED','CANCELLED')",BigDecimal.class,project));BigDecimal profit=salesInvoiced.subtract(purchaseInvoiced).setScale(2,RoundingMode.HALF_UP);BigDecimal margin=salesInvoiced.signum()==0?BigDecimal.ZERO:profit.multiply(BigDecimal.valueOf(100)).divide(salesInvoiced,2,RoundingMode.HALF_UP);return new WorkflowDtos.ProjectProfitability(project,salesOrdered,purchaseCommitted,salesInvoiced,purchaseInvoiced,profit,margin);}
 private BigDecimal sumWorkflow(String type,String project){return money(jdbc.queryForObject("SELECT COALESCE(SUM(total_amount),0) FROM workflow_document WHERE document_type=? AND project_no=? AND UPPER(COALESCE(status,''))<>'CANCELLED'",BigDecimal.class,type,project));}
 private void validate(WorkflowDtos.Document d,boolean create){if(d==null)throw new IllegalArgumentException("Workflow data is required");String t=type(d.documentType());if(!create)req(d.documentNo(),"Document number");if(d.documentDate()==null)throw new IllegalArgumentException("Document date is required");if(Set.of("PROJECT","SALES_ORDER").contains(t)&&trim(d.partyName()).isBlank())throw new IllegalArgumentException("Customer is required");if("PURCHASE_ORDER".equals(t)&&trim(d.partyName()).isBlank())throw new IllegalArgumentException("Supplier is required");if(!"PROJECT".equals(t)){String project=req(d.projectNo(),"Project number");requireDocument("PROJECT",project,"Project");}if("GRN".equals(t))requireDocument("PURCHASE_ORDER",req(d.parentNo(),"Purchase Order number"),"Purchase Order");if("DISPATCH".equals(t))requireDocument("SALES_ORDER",req(d.parentNo(),"Sales Order number"),"Sales Order");if("PURCHASE_ORDER".equals(t)&&!trim(d.parentNo()).isBlank())requireDocument("SALES_ORDER",trim(d.parentNo()),"Sales Order");}
 private void requireDocument(String type,String no,String label){if(docs.findByDocumentTypeAndDocumentNo(type,no).isEmpty())throw new IllegalArgumentException(label+" not found: "+no);}
 private void copy(WorkflowDtos.Document d,WorkflowDocumentEntity e,String assignedNo){String documentType=type(d.documentType());String partyName=trim(d.partyName()),projectNo=trim(d.projectNo()),parentNo=trim(d.parentNo()),customerPo=trim(d.customerPoNo());Integer partyId=d.partyId();if("PROJECT".equals(documentType)){projectNo=assignedNo;}else if("GRN".equals(documentType)){WorkflowDocumentEntity parent=docs.findByDocumentTypeAndDocumentNo("PURCHASE_ORDER",req(parentNo,"Purchase Order number")).orElseThrow(()->new IllegalArgumentException("Purchase Order not found: "+parentNo));projectNo=parent.getProjectNo();partyName=trim(parent.getPartyName());partyId=parent.getPartyId();}else if("DISPATCH".equals(documentType)){WorkflowDocumentEntity parent=docs.findByDocumentTypeAndDocumentNo("SALES_ORDER",req(parentNo,"Sales Order number")).orElseThrow(()->new IllegalArgumentException("Sales Order not found: "+parentNo));projectNo=parent.getProjectNo();partyName=trim(parent.getPartyName());partyId=parent.getPartyId();customerPo=trim(parent.getCustomerPoNo());}else if("PURCHASE_ORDER".equals(documentType)&&!parentNo.isBlank()){WorkflowDocumentEntity parent=docs.findByDocumentTypeAndDocumentNo("SALES_ORDER",parentNo).orElseThrow(()->new IllegalArgumentException("Sales Order not found: "+parentNo));projectNo=parent.getProjectNo();}e.setDocumentType(documentType);e.setDocumentNo(req(assignedNo,"Document number"));e.setDocumentDate(d.documentDate());e.setProjectNo(projectNo);e.setParentNo(parentNo);e.setPartyName(partyName);e.setPartyId(resolvePartyId(documentType,partyId,partyName));e.setCustomerPoNo(customerPo);e.setExpectedDate(d.expectedDate());e.setStatus(trim(d.status()).isBlank()?"DRAFT":trim(d.status()).toUpperCase(Locale.ROOT));e.setNotes(trim(d.notes()));}
 private Integer resolvePartyId(String documentType,Integer requestedId,String partyName){String expected=("PURCHASE_ORDER".equals(documentType)||"GRN".equals(documentType))?"SUPPLIER":"CUSTOMER";if(requestedId!=null&&requestedId>0){Long n=partyName.isBlank()?jdbc.queryForObject("SELECT COUNT(*) FROM party_master WHERE id=? AND UPPER(TRIM(party_type))=?",Long.class,requestedId,expected):jdbc.queryForObject("SELECT COUNT(*) FROM party_master WHERE id=? AND UPPER(TRIM(party_type))=? AND UPPER(TRIM(name))=UPPER(TRIM(?))",Long.class,requestedId,expected,partyName);if(n!=null&&n==1)return requestedId;}if(partyName.isBlank())return null;List<Integer> ids=jdbc.query("SELECT id FROM party_master WHERE UPPER(TRIM(party_type))=? AND UPPER(TRIM(name))=UPPER(TRIM(?)) ORDER BY id",(r,i)->r.getInt(1),expected,partyName);return ids.size()==1?ids.getFirst():null;}
 private WorkflowDtos.Document dto(WorkflowDocumentEntity e){var ls=lines.findByDocumentIdOrderByLineNo(e.getId()).stream().map(x->new WorkflowDtos.Line(x.getId(),x.getLineNo(),x.getItemCode(),x.getDescription(),x.getQuantity(),x.getRate(),x.getAmount())).toList();return new WorkflowDtos.Document(e.getId(),e.getDocumentType(),e.getDocumentNo(),e.getDocumentDate(),e.getProjectNo(),e.getParentNo(),e.getPartyName(),e.getPartyId(),e.getCustomerPoNo(),e.getExpectedDate(),e.getStatus(),e.getTotalAmount(),e.getNotes(),e.getRowVersion()==null?0:e.getRowVersion(),ls);}
 private static BigDecimal money(BigDecimal v){return (v==null?BigDecimal.ZERO:v).setScale(2,RoundingMode.HALF_UP);} private static String type(String s){s=trim(s).toUpperCase(Locale.ROOT);if(!TYPES.contains(s))throw new IllegalArgumentException("Unsupported workflow type: "+s);return s;} private static String trim(String s){return s==null?"":s.trim();} private static String req(String s,String n){s=trim(s);if(s.isBlank())throw new IllegalArgumentException(n+" is required");return s;} private static BigDecimal nonneg(BigDecimal v,String n){v=v==null?BigDecimal.ZERO:v;if(v.signum()<0)throw new IllegalArgumentException(n+" cannot be negative");return v;} private static <T> List<T> safe(List<T> v){return v==null?List.of():v;}
}
