package org.example.server.persistence.entity;

import org.example.server.util.BusinessClock;
import jakarta.persistence.*;
@Entity @Table(name="bank_statement_transaction")
public class BankStatementTransactionEntity {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @ManyToOne(fetch=FetchType.EAGER) @JoinColumn(name="import_id",nullable=false) private BankStatementImportEntity importBatch;
 @Column(name="source_row_number") private Integer sourceRowNumber; @Column(name="transaction_timestamp") private String transactionTimestamp; @Column(name="transaction_date") private String transactionDate; @Column(name="value_date") private String valueDate;
 @Column(name="original_description") private String originalDescription; @Column(name="original_reference") private String originalReference; @Column(name="debit_amount") private Double debitAmount; @Column(name="credit_amount") private Double creditAmount; private Double balance; private String status;
 @Column(name="suggested_match_type") private String suggestedMatchType; @Column(name="suggested_match_id") private Integer suggestedMatchId; @Column(name="suggested_confidence") private Double suggestedConfidence; private String notes;
 @Column(name="transaction_fingerprint",nullable=false,unique=true) private String transactionFingerprint; @Column(name="created_at") private String createdAt; @Column(name="updated_at") private String updatedAt;
 @PrePersist void create(){String n=BusinessClock.now().toString();if(createdAt==null)createdAt=n;updatedAt=n;if(status==null)status="UNMATCHED";} @PreUpdate void update(){updatedAt=BusinessClock.now().toString();}
 public Long getId(){return id;} public BankStatementImportEntity getImportBatch(){return importBatch;} public void setImportBatch(BankStatementImportEntity v){importBatch=v;} public Integer getSourceRowNumber(){return sourceRowNumber;} public void setSourceRowNumber(Integer v){sourceRowNumber=v;} public String getTransactionTimestamp(){return transactionTimestamp;} public void setTransactionTimestamp(String v){transactionTimestamp=v;} public String getTransactionDate(){return transactionDate;} public void setTransactionDate(String v){transactionDate=v;} public String getValueDate(){return valueDate;} public void setValueDate(String v){valueDate=v;} public String getOriginalDescription(){return originalDescription;} public void setOriginalDescription(String v){originalDescription=v;} public String getOriginalReference(){return originalReference;} public void setOriginalReference(String v){originalReference=v;} public Double getDebitAmount(){return debitAmount;} public void setDebitAmount(Double v){debitAmount=v;} public Double getCreditAmount(){return creditAmount;} public void setCreditAmount(Double v){creditAmount=v;} public Double getBalance(){return balance;} public void setBalance(Double v){balance=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public String getSuggestedMatchType(){return suggestedMatchType;} public void setSuggestedMatchType(String v){suggestedMatchType=v;} public Integer getSuggestedMatchId(){return suggestedMatchId;} public void setSuggestedMatchId(Integer v){suggestedMatchId=v;} public Double getSuggestedConfidence(){return suggestedConfidence;} public void setSuggestedConfidence(Double v){suggestedConfidence=v;} public String getNotes(){return notes;} public void setNotes(String v){notes=v;} public String getTransactionFingerprint(){return transactionFingerprint;} public void setTransactionFingerprint(String v){transactionFingerprint=v;} public String getCreatedAt(){return createdAt;} public String getUpdatedAt(){return updatedAt;}
}
