version=@project.version@
buildRevision=@project.version@
buildTime=@maven.build.timestamp@
databaseMigrationVersion=1
databaseMinCompatibleVersion=1
databaseMaxCompatibleVersion=1
databaseCompatibilitySinceVersion=7.2.2
workspaceSchemaVersion=1
