package org.example.controller;

import org.example.util.OwnedAlert;
import javafx.application.Platform;import javafx.beans.property.*;import javafx.fxml.FXML;import javafx.scene.Node;import javafx.scene.control.*;import javafx.stage.FileChooser;import org.example.database.DatabaseManager;import org.example.model.Sales;import org.example.navigation.NavigationManager;
import org.example.service.SalesService;import org.example.util.IconFactory;import java.io.*;import java.nio.charset.StandardCharsets;import java.sql.*;import java.util.*;
public class PaymentHistoryController{
 public record Row(String date,String reference,String from,String mode,double amount,String status,String notes){}@FXML private Label invoiceNo,customer,total,paid,balance;@FXML private TableView<Row>table;@FXML private TableColumn<Row,String>date,reference,from,mode,status,notes;@FXML private TableColumn<Row,Number>amount;private Sales sale;private final List<Row>all=new ArrayList<>();
 @FXML public void initialize(){
        configureExplicitTableHeaderIcons();sale=new SalesService().getByInvoice(SalesScreenContext.invoice());if(sale==null)return;invoiceNo.setText(sale.getInvoiceNo());customer.setText(sale.getCustomer().getName());total.setText(m(sale.getTotalAmount()));paid.setText(m(sale.getPaidAmount()));balance.setText(m(sale.getBalanceAmount()));date.setCellValueFactory(x->new SimpleStringProperty(x.getValue().date()));reference.setCellValueFactory(x->new SimpleStringProperty(x.getValue().reference()));from.setCellValueFactory(x->new SimpleStringProperty(x.getValue().from()));mode.setCellValueFactory(x->new SimpleStringProperty(x.getValue().mode()));amount.setCellValueFactory(x->new SimpleDoubleProperty(x.getValue().amount()));amount.setCellFactory(c->new TableCell<>(){protected void updateItem(Number v,boolean e){super.updateItem(v,e);setText(e||v==null?null:m(v.doubleValue()));}});status.setCellValueFactory(x->new SimpleStringProperty(x.getValue().status()));notes.setCellValueFactory(x->new SimpleStringProperty(x.getValue().notes()));table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);load();Platform.runLater(this::wire);}
 private void load(){all.clear();try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM payment_record WHERE document_type='SALE' AND document_id=? ORDER BY payment_date DESC,id DESC")){p.setInt(1,sale.getId());try(ResultSet r=p.executeQuery()){while(r.next())all.add(new Row(r.getString("payment_date"),n(r.getString("reference_no")),sale.getCustomer().getName(),r.getString("payment_mode"),r.getDouble("amount"),"Received",n(r.getString("notes"))));}}catch(Exception e){error(e);}table.getItems().setAll(all);}
 private void wire(){for(Node x:table.getScene().getRoot().lookupAll(".button")){if(!(x instanceof Button b))continue;String s=n(b.getText()).toLowerCase();if(s.contains("record"))b.setGraphic(IconFactory.icon("payment"));else if(s.contains("invoice"))b.setGraphic(IconFactory.icon("document"));else if(s.contains("export")){b.setGraphic(IconFactory.icon("download"));b.setOnAction(e->export());}else if(s.equals("clear"))b.setOnAction(e->table.getItems().setAll(all));else if(s.equals("filter"))b.setOnAction(e->filter());}}
 @FXML private void filter(){String modeValue=null;for(Node x:table.getScene().getRoot().lookupAll(".combo-box"))if(x instanceof ComboBox<?>b&&b.getValue()!=null&&!b.getValue().toString().startsWith("All"))modeValue=b.getValue().toString();String f=modeValue;table.getItems().setAll(all.stream().filter(r->f==null||r.mode().equalsIgnoreCase(f)).toList());}
 @FXML private void export(){FileChooser f=new FileChooser();f.setInitialFileName("Payment_History_"+sale.getInvoiceNo()+".csv");f.getExtensionFilters().add(new FileChooser.ExtensionFilter("CSV File","*.csv"));File out=f.showSaveDialog(table.getScene().getWindow());if(out==null)return;try(Writer w=new OutputStreamWriter(new FileOutputStream(out),StandardCharsets.UTF_8)){w.write("Date,Reference,Received From,Mode,Amount,Status,Notes\n");for(Row r:table.getItems())w.write(csv(r.date())+","+csv(r.reference())+","+csv(r.from())+","+csv(r.mode())+","+r.amount()+","+csv(r.status())+","+csv(r.notes())+"\n");info("Payment history exported.");}catch(Exception e){error(e);}}
 @FXML private void clear(){table.getItems().setAll(all);}
 @FXML private void record(){SalesScreenContext.select(sale.getInvoiceNo());NavigationManager.getInstance().loadPage("/fxml/pages/RecordPayment.fxml");}@FXML private void invoice(){SalesScreenContext.select(sale.getInvoiceNo());NavigationManager.getInstance().loadPage("/fxml/pages/RecordPayment.fxml");}private String csv(String s){return "\""+n(s).replace("\"","\"\"")+"\"";}private void info(String s){new OwnedAlert(Alert.AlertType.INFORMATION,s).showAndWait();}private void error(Exception e){new OwnedAlert(Alert.AlertType.ERROR,e.getMessage()).showAndWait();}private String m(double v){return String.format("₹ %,.2f",v);}private String n(String s){return s==null?"":s;}


    private void configureExplicitTableHeaderIcons() {
        IconFactory.applyTableHeaderIcon(date, "calendar");
        IconFactory.applyTableHeaderIcon(reference, "document");
        IconFactory.applyTableHeaderIcon(from, "customer");
        IconFactory.applyTableHeaderIcon(mode, "payment");
        IconFactory.applyTableHeaderIcon(amount, "currency");
        IconFactory.applyTableHeaderIcon(status, "status");
        IconFactory.applyTableHeaderIcon(notes, "document");
    }
}
