package org.example.controller;
import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import javafx.scene.control.cell.CheckBoxTableCell;import org.example.database.DatabaseManager;import java.sql.*;import java.util.*;
public class PermissionMatrixController {
 private static String requestedRole; public static void requestRole(String r){requestedRole=r;}
 @FXML private ComboBox<String> cmbRole;@FXML private TableView<Row> table;@FXML private TableColumn<Row,String> colModule,colAction,colDescription;@FXML private TableColumn<Row,Boolean> colAllowed;@FXML private Label lblGranted,lblDenied,lblHint;
 private final ObservableList<Row> rows=FXCollections.observableArrayList();
 @FXML private void initialize(){colModule.setCellValueFactory(v->v.getValue().module);colAction.setCellValueFactory(v->v.getValue().action);colDescription.setCellValueFactory(v->v.getValue().description);colAllowed.setCellValueFactory(v->v.getValue().allowed);colAllowed.setCellFactory(CheckBoxTableCell.forTableColumn(colAllowed));table.setEditable(true);colAllowed.setEditable(true);table.setItems(rows);loadRoles();cmbRole.valueProperty().addListener((o,a,b)->load(b));if(requestedRole!=null&&cmbRole.getItems().contains(requestedRole))cmbRole.setValue(requestedRole);else if(!cmbRole.getItems().isEmpty())cmbRole.getSelectionModel().selectFirst();requestedRole=null;}
 private void loadRoles(){try(Connection c=DatabaseManager.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT role_name FROM roles WHERE active=1 ORDER BY role_name")){while(r.next())cmbRole.getItems().add(r.getString(1));}catch(Exception ignored){}}
 private void load(String role){rows.clear();if(role==null)return;boolean admin=role.equalsIgnoreCase("ADMIN");String q="SELECT p.id,p.module_name,p.action_name,p.description,COALESCE(rp.allowed,0) FROM permissions p JOIN roles r ON r.role_name=? LEFT JOIN role_permission rp ON rp.permission_id=p.id AND rp.role_id=r.id WHERE p.active=1 ORDER BY p.module_name,p.action_name";try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,role);try(ResultSet r=p.executeQuery()){while(r.next())rows.add(new Row(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),admin||r.getBoolean(5)));}}catch(Exception ignored){}update();lblHint.setText(admin?"Administrator receives full access by system policy.":"Configure granular access for "+role+".");}
 @FXML private void save(){String role=cmbRole.getValue();if(role==null||role.equalsIgnoreCase("ADMIN"))return;try(Connection c=DatabaseManager.getConnection()){c.setAutoCommit(false);long rid;try(PreparedStatement p=c.prepareStatement("SELECT id FROM roles WHERE role_name=?")){p.setString(1,role);try(ResultSet r=p.executeQuery()){if(!r.next())return;rid=r.getLong(1);}}try(PreparedStatement d=c.prepareStatement("DELETE FROM role_permission WHERE role_id=?")){d.setLong(1,rid);d.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO role_permission(role_id,permission_id,allowed) VALUES(?,?,?)")){for(Row x:rows){p.setLong(1,rid);p.setLong(2,x.id);p.setBoolean(3,x.allowed.get());p.addBatch();}p.executeBatch();}c.commit();}catch(Exception e){new Alert(Alert.AlertType.ERROR,e.getMessage()).showAndWait();}update();}
 @FXML private void reset(){load(cmbRole.getValue());}@FXML private void grantAll(){rows.forEach(x->x.allowed.set(true));update();}@FXML private void revokeAll(){if(!"ADMIN".equalsIgnoreCase(cmbRole.getValue()))rows.forEach(x->x.allowed.set(false));update();}@FXML private void back(){DashboardController.navigateFromChildPage("Role Management","/fxml/pages/RoleManagement.fxml");}
 private void update(){long g=rows.stream().filter(x->x.allowed.get()).count();lblGranted.setText(String.valueOf(g));lblDenied.setText(String.valueOf(rows.size()-g));}
 public static class Row{final long id;final StringProperty module=new SimpleStringProperty(),action=new SimpleStringProperty(),description=new SimpleStringProperty();final BooleanProperty allowed=new SimpleBooleanProperty();Row(long i,String m,String a,String d,boolean x){id=i;module.set(m);action.set(a);description.set(d);allowed.set(x);}}
}
