package org.example.controller;

import org.example.util.OwnedAlert;
import javafx.application.Platform;import javafx.collections.FXCollections;import javafx.fxml.FXML;import javafx.scene.Node;import javafx.scene.control.*;import javafx.stage.FileChooser;import org.example.config.ConfigManager;import org.example.dao.SalesDAO;import org.example.database.DatabaseManager;import org.example.model.Sales;import org.example.navigation.NavigationManager;import org.example.service.NotificationService;import org.example.util.IconFactory;import java.sql.*;import java.time.LocalDate;
public class RecordPaymentController{
 @FXML private Label invoiceNo,customer,invoiceDate,dueDate,total,paid,balance,after;@FXML private DatePicker paymentDate;@FXML private ComboBox<String>mode;@FXML private TextField reference,amount;@FXML private TextArea notes;private Sales sale;
 @FXML public void initialize(){sale=new SalesDAO().getByInvoice(SalesScreenContext.invoice());if(sale==null)return;invoiceNo.setText(sale.getInvoiceNo());customer.setText(sale.getCustomer().getName());invoiceDate.setText(sale.getInvoiceDate().toString());dueDate.setText(sale.getDueDate()==null?"Not set":sale.getDueDate().toString());total.setText(m(sale.getTotalAmount()));if(paid!=null)paid.setText(m(sale.getPaidAmount()));if(balance!=null)balance.setText(m(sale.getBalanceAmount()));after.setText(m(sale.getBalanceAmount()));paymentDate.setValue(LocalDate.now());mode.setItems(FXCollections.observableArrayList("Bank Transfer","Cash","Cheque","UPI","Card","Other"));mode.setValue("Bank Transfer");amount.setText(String.format(java.util.Locale.ROOT,"%.2f",sale.getBalanceAmount()));amount.textProperty().addListener((o,a,b)->{try{after.setText(m(sale.getBalanceAmount()-Double.parseDouble(b)));}catch(Exception e){after.setText(m(sale.getBalanceAmount()));}});Platform.runLater(this::wireUi);}
 private void wireUi(){for(Node x:amount.getScene().getRoot().lookupAll(".combo-box"))if(x instanceof ComboBox<?>b&&"Select account".equals(b.getPromptText())){@SuppressWarnings("unchecked")ComboBox<String>box=(ComboBox<String>)b;String bank=ConfigManager.get("payment.bankName","").trim(),account=ConfigManager.get("payment.accountNumber","").trim();if(!bank.isBlank()&&!account.isBlank()){box.getItems().setAll(bank+" - "+mask(account));box.getSelectionModel().selectFirst();}else box.setPromptText("Configure bank account in Settings");}for(Node x:amount.getScene().getRoot().lookupAll(".button")){if(!(x instanceof Button b))continue;String s=b.getText()==null?"":b.getText().toLowerCase();String key=s.contains("save")?"payment":s.contains("print")?"print":s.contains("receipt")?"email":s.contains("whatsapp")?"whatsapp":s.contains("invoice")?"document":s.contains("browse")?"download":s.contains("cancel")?"return":null;if(key!=null)b.setGraphic(IconFactory.icon(key));if(s.contains("view invoice"))b.setOnAction(e->cancel());if(s.contains("send whatsapp")||s.contains("send receipt")||s.contains("print receipt"))b.setOnAction(e->new OwnedAlert(Alert.AlertType.INFORMATION,"Save the payment first; receipt actions become available from Payment History.").showAndWait());}}
 private String mask(String v){return v.length()<=4?v:"••••"+v.substring(v.length()-4);}
 @FXML private void save(){try{double v=Double.parseDouble(amount.getText());if(v<=0||v>sale.getBalanceAmount())throw new IllegalArgumentException("Enter an amount up to "+m(sale.getBalanceAmount()));try(Connection c=DatabaseManager.getConnection()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO payment_record(document_type,document_id,payment_date,amount,payment_mode,reference_no,notes,created_by) VALUES('SALE',?,?,?,?,?,?,?)");PreparedStatement u=c.prepareStatement("UPDATE sales_header SET paid_amount=COALESCE(paid_amount,0)+?,payment_status=CASE WHEN COALESCE(paid_amount,0)+?>=total_amount THEN 'PAID' ELSE 'PARTIAL' END WHERE id=?")){p.setInt(1,sale.getId());p.setString(2,paymentDate.getValue().toString());p.setDouble(3,v);p.setString(4,mode.getValue());p.setString(5,reference.getText());p.setString(6,notes.getText());p.setString(7,"Admin");p.executeUpdate();u.setDouble(1,v);u.setDouble(2,v);u.setInt(3,sale.getId());u.executeUpdate();c.commit();}catch(Exception e){c.rollback();throw e;}}NotificationService.add("Payment received for "+sale.getInvoiceNo());new OwnedAlert(Alert.AlertType.INFORMATION,"Payment saved successfully.").showAndWait();history();}catch(Exception e){new OwnedAlert(Alert.AlertType.ERROR,e.getMessage()).showAndWait();}}
 @FXML private void cancel(){NavigationManager.getInstance().loadPage("/fxml/pages/SalesInvoiceDetails.fxml");}@FXML private void history(){NavigationManager.getInstance().loadPage("/fxml/pages/PaymentHistory.fxml");}private String m(double v){return String.format("₹ %,.2f",Math.max(0,v));}
 @FXML private void browseFile(){FileChooser chooser=new FileChooser();chooser.setTitle("Choose payment attachment");java.io.File file=chooser.showOpenDialog(amount.getScene().getWindow());if(file!=null)notes.appendText((notes.getText().isBlank()?"":"\n")+"Attachment: "+file.getAbsolutePath());}
 @FXML private void receiptUnavailable(){new OwnedAlert(Alert.AlertType.INFORMATION,"Save the payment first; receipt actions become available from Payment History.").showAndWait();}

}
