package org.example.controller;
import javafx.beans.property.*;import javafx.collections.*;import javafx.fxml.FXML;import javafx.scene.control.*;import org.example.database.DatabaseManager;import org.example.util.*;import java.sql.*;
public class RoleManagementController {
 @FXML private TableView<RoleRow> roleTable; @FXML private TableColumn<RoleRow,String> colName,colDescription,colStatus; @FXML private TableColumn<RoleRow,Number> colUsers; @FXML private Label lblRoles,lblAssigned,lblCustom;
 private final ObservableList<RoleRow> rows=FXCollections.observableArrayList();
 @FXML private void initialize(){colName.setCellValueFactory(v->v.getValue().name);colDescription.setCellValueFactory(v->v.getValue().description);colUsers.setCellValueFactory(v->v.getValue().users);colStatus.setCellValueFactory(v->v.getValue().status);roleTable.setItems(rows);roleTable.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);refresh();}
 @FXML private void refresh(){rows.clear();try(Connection c=DatabaseManager.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT r.id,r.role_name,r.description,r.active,COUNT(u.id) cnt FROM roles r LEFT JOIN users u ON u.role_id=r.id OR (u.role_id IS NULL AND u.role=r.role_name) GROUP BY r.id ORDER BY r.role_name")){while(r.next())rows.add(new RoleRow(r.getLong(1),r.getString(2),r.getString(3),r.getInt(5),r.getBoolean(4)));}catch(Exception e){alert("Roles could not be loaded",e.getMessage());}lblRoles.setText(String.valueOf(rows.size()));lblAssigned.setText(String.valueOf(rows.stream().mapToInt(x->x.users.get()).sum()));lblCustom.setText(String.valueOf(rows.stream().filter(x->!x.name.get().equalsIgnoreCase("ADMIN")).count()));}
 @FXML private void addRole(){TextInputDialog d=new TextInputDialog();d.setTitle("Add Role");d.setHeaderText("Create a new system role");d.setContentText("Role name:");d.showAndWait().map(String::trim).filter(x->!x.isBlank()).ifPresent(n->{try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO roles(role_name,description,active) VALUES(?,?,1)")){p.setString(1,n.toUpperCase());p.setString(2,"Custom ERP role");p.executeUpdate();refresh();}catch(Exception e){alert("Role could not be created",e.getMessage());}});}
 @FXML private void editRole(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();if(x==null)return;TextInputDialog d=new TextInputDialog(x.description.get());d.setTitle("Edit Role");d.setHeaderText(x.name.get());d.setContentText("Description:");d.showAndWait().ifPresent(v->{try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement("UPDATE roles SET description=? WHERE id=?")){p.setString(1,v.trim());p.setLong(2,x.id);p.executeUpdate();refresh();}catch(Exception e){alert("Role could not be updated",e.getMessage());}});}
 @FXML private void deleteRole(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();if(x==null||x.name.get().equalsIgnoreCase("ADMIN"))return;Alert a=new Alert(Alert.AlertType.CONFIRMATION,"Delete role "+x.name.get()+"?",ButtonType.YES,ButtonType.NO);if(a.showAndWait().orElse(ButtonType.NO)!=ButtonType.YES)return;try(Connection c=DatabaseManager.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM roles WHERE id=?")){p.setLong(1,x.id);p.executeUpdate();refresh();}catch(Exception e){alert("Role could not be deleted","Remove assigned users first. "+e.getMessage());}}
 @FXML private void openPermissions(){RoleRow x=roleTable.getSelectionModel().getSelectedItem();PermissionMatrixController.requestRole(x==null?null:x.name.get());DashboardController.navigateFromChildPage("Permission Matrix","/fxml/pages/PermissionMatrix.fxml");}
 @FXML private void back(){DashboardController.navigateFromChildPage("User Access & Permissions","/fxml/pages/UserAccess.fxml");}
 private void alert(String h,String c){Alert a=new Alert(Alert.AlertType.ERROR);a.setHeaderText(h);a.setContentText(c);a.showAndWait();}
 public static class RoleRow{final long id;final StringProperty name=new SimpleStringProperty(),description=new SimpleStringProperty(),status=new SimpleStringProperty();final IntegerProperty users=new SimpleIntegerProperty();RoleRow(long i,String n,String d,int u,boolean a){id=i;name.set(n);description.set(d==null?"":d);users.set(u);status.set(a?"Active":"Inactive");}}
}
