package org.example.controller;
import javafx.application.Platform;import javafx.beans.property.SimpleStringProperty;import javafx.fxml.*;import javafx.scene.*;import javafx.scene.control.*;import javafx.scene.layout.StackPane;import org.example.dao.SalesDAO;import org.example.model.*;import org.example.navigation.NavigationManager;import org.example.service.*;import org.example.util.IconFactory;import java.awt.Desktop;import java.nio.file.Path;import java.time.format.DateTimeFormatter;
public class SalesDetailController{
 @FXML private Label invoiceNo,status,customer,contact,invoiceDate,dueDate,total,paid,balance,subtotal,tax,grand,notes;@FXML private TableView<SalesLine> items;@FXML private TableColumn<SalesLine,String> cItem,cCode,cQty,cUnit,cRate,cTax,cAmount;private Sales sale;
 @FXML public void initialize(){
        configureExplicitTableHeaderIcons();String no=SalesScreenContext.invoice();if(no==null){back();return;}sale=new SalesDAO().getByInvoice(no);if(sale==null)return;invoiceNo.setText("Invoice "+sale.getInvoiceNo());status.setText(sale.getPaymentStatus());customer.setText(sale.getCustomer().getName());contact.setText(n(sale.getCustomer().getPhone())+"\n"+n(sale.getCustomer().getEmail())+"\n"+n(sale.getCustomer().getAddress()));invoiceDate.setText(sale.getInvoiceDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));dueDate.setText(sale.getDueDate()==null?"Not set":sale.getDueDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));total.setText(m(sale.getTotalAmount()));paid.setText(m(sale.getPaidAmount()));balance.setText(m(sale.getBalanceAmount()));subtotal.setText(m(sale.getSubtotal()));tax.setText(m(sale.getGstAmount()));grand.setText(m(sale.getTotalAmount()));notes.setText(n(sale.getRemarks()));cItem.setCellValueFactory(x->new SimpleStringProperty(x.getValue().getItemDescription()));cCode.setCellValueFactory(x->new SimpleStringProperty(x.getValue().getItemCode()));cQty.setCellValueFactory(x->new SimpleStringProperty(String.valueOf(x.getValue().getQuantity())));cUnit.setCellValueFactory(x->new SimpleStringProperty("Nos"));cRate.setCellValueFactory(x->new SimpleStringProperty(m(x.getValue().getRate())));cTax.setCellValueFactory(x->new SimpleStringProperty(x.getValue().getGstPercent()+"%"));cAmount.setCellValueFactory(x->new SimpleStringProperty(m(x.getValue().getTotalAmount())));items.getItems().setAll(sale.getLines());items.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_LAST_COLUMN);Platform.runLater(this::prepareUi);}
 private void prepareUi(){Parent root=items.getScene().getRoot();for(Node x:root.lookupAll(".tab-pane"))if(x instanceof TabPane t&&t.getTabs().size()>1)t.getTabs().remove(1,t.getTabs().size());for(Node x:root.lookupAll(".button")){if(!(x instanceof Button b))continue;String s=n(b.getText()).toLowerCase();String key=s.contains("edit")?"edit":s.contains("print")?"print":s.contains("pdf")?"download":s.contains("payment history")?"payment":s.contains("record payment")?"payment":s.contains("more")?"settings":null;if(key!=null)b.setGraphic(IconFactory.icon(key));if(s.contains("edit")&&b.getOnAction()==null)b.setOnAction(e->edit());if(s.contains("more")&&b.getOnAction()==null){b.setText("Back to Register");b.setGraphic(IconFactory.icon("return"));b.setOnAction(e->back());}}}
 @FXML private void edit(){try{FXMLLoader l=new FXMLLoader(getClass().getResource("/fxml/pages/Sale.fxml"));Parent r=l.load();((SalesController)l.getController()).loadSale(sale);StackPane pane=(StackPane)items.getScene().lookup("#contentPane");pane.getChildren().setAll(r);}catch(Exception e){error(e);}}
 @FXML private void whatsapp(){try{String phone=n(sale.getCustomer().getPhone()).replaceAll("\\D","");if(phone.length()==10)phone="91"+phone;if(phone.isBlank())throw new IllegalStateException("Customer mobile number is missing. Update it in Customer Master.");Path pdf=InvoicePdfService.sales(sale);WhatsappService.openWhatsappWithMessage(phone,PaymentMessageService.salesMessage(sale),pdf,PaymentMessageService.configuredQrPath());info("WhatsApp is ready. The invoice and configured UPI QR are on the clipboard for attachment.");}catch(Exception e){error(e);}}
 @FXML private void recordPayment(){SalesScreenContext.select(sale.getInvoiceNo());NavigationManager.getInstance().loadPage("/fxml/pages/RecordPayment.fxml");}@FXML private void history(){SalesScreenContext.select(sale.getInvoiceNo());NavigationManager.getInstance().loadPage("/fxml/pages/PaymentHistory.fxml");}@FXML private void back(){NavigationManager.getInstance().loadPage("/fxml/pages/SalesList.fxml");}@FXML private void pdf(){try{Path p=InvoicePdfService.sales(sale);Desktop.getDesktop().open(p.toFile());}catch(Exception e){error(e);}}
 private void info(String s){new Alert(Alert.AlertType.INFORMATION,s).showAndWait();}private void error(Exception e){new Alert(Alert.AlertType.ERROR,e.getMessage()).showAndWait();}private String m(double v){return String.format("₹ %,.2f",v);}private String n(String s){return s==null?"":s;}


    private void configureExplicitTableHeaderIcons() {
        IconFactory.applyTableHeaderIcon(cItem, "item");
        IconFactory.applyTableHeaderIcon(cCode, "document");
        IconFactory.applyTableHeaderIcon(cQty, "quantity");
        IconFactory.applyTableHeaderIcon(cUnit, "unit");
        IconFactory.applyTableHeaderIcon(cRate, "currency");
        IconFactory.applyTableHeaderIcon(cTax, "tax");
        IconFactory.applyTableHeaderIcon(cAmount, "currency");
    }
}
