package org.example.bank;

import org.example.api.bank.BankStatementApiClient;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.security.MessageDigest;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

public final class KotakBankStatementCsvParser {
 private static final DateTimeFormatter TS_IN=DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"); private static final DateTimeFormatter DATE_IN=DateTimeFormatter.ofPattern("dd-MM-yyyy");
 public ParsedStatement parse(Path file)throws IOException{List<String> lines=Files.readAllLines(file,StandardCharsets.UTF_8);String account="",accountHolder="",currency="INR",branch="",from="",to="";int header=-1;if(lines.size()>1){List<String> holderRow=parseLine(lines.get(1));if(!holderRow.isEmpty())accountHolder=holderRow.get(0).trim();}for(int i=0;i<lines.size();i++){List<String>c=parseLine(lines.get(i));if(!c.isEmpty()&&"Sl. No.".equalsIgnoreCase(c.get(0).trim())){header=i;break;}for(int j=0;j+1<c.size();j++){String k=c.get(j).trim();String v=c.get(j+1).trim();if(k.equalsIgnoreCase("Account No."))account=v;else if(k.equalsIgnoreCase("Currency"))currency=v;else if(k.equalsIgnoreCase("Branch"))branch=v;else if(k.equalsIgnoreCase("Period")){String[]p=v.replace("From ","").split(" To ");if(p.length==2){from=isoDate(p[0].replace('/','-'));to=isoDate(p[1].replace('/','-'));}}}}
  if(header<0)throw new IllegalArgumentException("Kotak transaction header was not found in the CSV file.");List<BankStatementApiClient.ImportRow>rows=new ArrayList<>();Double opening=null,closing=null;int source=0;for(int i=header+1;i<lines.size();i++){List<String>c=parseLine(lines.get(i));if(c.size()<9||c.get(0).trim().isBlank())continue;try{source=Integer.parseInt(c.get(0).trim());String ts=isoTimestamp(c.get(1));String date=ts.substring(0,10);String value=isoDate(c.get(2));String desc=c.get(3).trim();String ref=c.get(4).trim();double amount=num(c.get(5));String dir=c.get(6).trim().toUpperCase(Locale.ROOT);double bal=num(c.get(7));double debit="DR".equals(dir)?amount:0,credit="CR".equals(dir)?amount:0;if(opening==null)opening=bal-credit+debit;closing=bal;String fp=sha256(account+"|"+ts+"|"+ref+"|"+String.format(Locale.ROOT,"%.2f",debit)+"|"+String.format(Locale.ROOT,"%.2f",credit)+"|"+String.format(Locale.ROOT,"%.2f",bal));rows.add(new BankStatementApiClient.ImportRow(source,ts,date,value,desc,ref,debit,credit,bal,fp));}catch(Exception ignored){}}
  if(rows.isEmpty())throw new IllegalArgumentException("No usable transactions were found in the Kotak CSV file.");if(from.isBlank())from=rows.getFirst().transactionDate();if(to.isBlank())to=rows.getLast().transactionDate();return new ParsedStatement("Kotak Mahindra Bank",account,accountHolder,from,to,currency,branch,opening,closing,sha256(Files.readAllBytes(file)),file.getFileName().toString(),Files.readString(file,StandardCharsets.UTF_8),rows);
 }
 public static String sha256(Path p)throws IOException{return sha256(Files.readAllBytes(p));} private static String sha256(byte[]b){try{MessageDigest m=MessageDigest.getInstance("SHA-256");byte[]d=m.digest(b);StringBuilder s=new StringBuilder();for(byte x:d)s.append(String.format("%02x",x));return s.toString();}catch(Exception e){throw new IllegalStateException(e);}} private static String sha256(String s){return sha256(s.getBytes(StandardCharsets.UTF_8));}
 private static double num(String s){String x=s==null?"":s.replace(",","").replace("₹","").trim();return x.isBlank()?0:Double.parseDouble(x);} private static String isoDate(String s){String x=s.trim().replace('/','-');try{return LocalDate.parse(x,DATE_IN).toString();}catch(Exception e){return LocalDate.parse(x,DateTimeFormatter.ofPattern("dd-MM-yyyy")).toString();}} private static String isoTimestamp(String s){return LocalDateTime.parse(s.trim(),TS_IN).toString();}
 private static List<String> parseLine(String line){List<String>out=new ArrayList<>();StringBuilder cur=new StringBuilder();boolean q=false;for(int i=0;i<line.length();i++){char ch=line.charAt(i);if(ch=='\"'){if(q&&i+1<line.length()&&line.charAt(i+1)=='\"'){cur.append('"');i++;}else q=!q;}else if(ch==','&&!q){out.add(cur.toString());cur.setLength(0);}else cur.append(ch);}out.add(cur.toString());return out;}
 public record ParsedStatement(String bankName,String accountNumber,String accountHolder,String statementFrom,String statementTo,String currency,String branch,Double openingBalance,Double closingBalance,String sourceFingerprint,String sourceFileName,String sourceCsv,List<BankStatementApiClient.ImportRow> rows){}
}
